### ISSUE TITLE
configure finds MPI and says 'MPI Support is ON` but then binaries aren't linked with MPI libraries

### ISSUE THREAD

**Issue by yurivict** [LLNL/conduit#1010]
Portion of the configure log:
```
-- MPI Support is ON
-- Enable FindMPI:  ON
-- Found MPI_C: /usr/local/mpi/openmpi/lib/libmpi.so (found version "3.1")
-- Found MPI_CXX: /usr/local/mpi/openmpi/lib/libmpi_cxx.so (found version "3.1")
-- Found MPI_Fortran: /usr/local/mpi/openmpi/lib/libmpi_usempi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- BLT MPI Compile Flags:  -fexceptions;-pthread
-- BLT MPI Include Paths:  /usr/local/mpi/openmpi/include;/usr/local/mpi/openmpi/lib
-- BLT MPI Libraries:      /usr/local/mpi/openmpi/lib/libmpi.so;/usr/local/mpi/openmpi/lib/libmpi_cxx.so;/usr/local/mpi/openmpi/lib/libmpi_usempi.so;/usr/local/mpi/openmpi/lib/libmpi_mpifh.so
-- BLT MPI Link Flags:     SHELL:-Wl,-rpath=-Wl,-rpath=/usr/local/lib/gcc11 -Wl,-rpath -Wl,/usr/local/mpi/openmpi/lib -Wl,--enable-new-dtags -pthread
-- MPI Executable:       /usr/local/mpi/openmpi/bin/mpiexec
-- MPI Num Proc Flag:    -n
-- MPI Command Append:
-- Using MPI Fortran header: mpif.h
```

```ldd -a work/stage/usr/local/bin/conduit_relay_io_ls  | grep mpi``` doesn't show that MPI libraries are linked.
And there are no static MPI libraries present.

Version: 0.8.3
clang-14
FreeBSD 13.1

**Comment by cyrush** [comment]
@yurivict Conduit MPI features are only in a few libraries. `conduit_relay_io_ls` does not leverage MPI directly, so it does not link MPI. 

The only exception to this will be the case when Conduit is build against an HDF5 that depends on MPI, then MPI libs should be propagated to conduit relay dependent libs and exes.

**Comment by yurivict** [comment]
This works, thanks!

What is the way to change MPI implementation in conduit?
When I set ```-DENABLE_MPI=ON -DMPI_HOME=/usr/local``` in order to choose mpich which is installed in ```/usr/local``` it still uses OpenMPI from ```/usr/local/mpi/openmpi```.

**Comment by yurivict** [comment]
I'll create a separate issue for the next problem.
