### ISSUE TITLE
The Node::reset() method seems to be missing from the Conduit C interface

### ISSUE THREAD

**Issue by acbauer** [LLNL/conduit#1019]
I don't see any reset() method in conduit_node.h to correspond to the public Node::reset() method. The Node::reset() method is used in the Blueprint AMR examples so I'm thinking that if users wanted to try doing those examples (like I did) through the Conduit C interface it may be a bit difficult.

Is this intentional or an oversight that reset() isn't in the Conduit C interface? I didn't check on the Python interface but someone more familiar with Conduit may want to check that as well.

Thanks,
Andy

**Comment by cyrush** [comment]
Not an intentional omission -- we can add it for both C and fortran.

I double checked, it is in the Python interface. 

(C++ and Python are most used, there are more c and fortran gaps, but we are happy to address them)

**Comment by cyrush** [comment]
@acbauer I added this in #1021

**Comment by acbauer** [comment]
Awesome -- very much appreciated!
