### ISSUE TITLE
How to visualize mixed mesh

### ISSUE THREAD

**Issue by keyu-Li** [LLNL/conduit#1029]
I am interested in mixed shapes topology. But I don't know how to visualize it, can you provide an example? Thanks!

**Comment by cyrush** [comment]
@keyu-Li  Conduit allows this in the Blueprint standard -- but Ascent hasn't added support for this case yet.

The `conduit::blueprint::mesh::examples::braid` with `mesh_type` == `mixed` or `mixed_2d` will create example meshs with mixed elements.
