### ISSUE TITLE
Question: why packaged with blt?

### ISSUE THREAD

**Issue by vsoch** [LLNL/conduit#1042]
Hi! Another question for you! Is there a reason conduit ships with the release that has blt? e.g., this URL pattern:

```
https://github.com/LLNL/conduit/releases/download/v${version}/conduit-v${version}-src-with-blt.tar.gz
```
I'm wondering why it's not OK to build blt first, and then do a build of conduit that can include that?

**Comment by cyrush** [comment]
@vsoch 

The source tarballs/zips generated by github do not include submodules, so we provide a tarball that includes BLT to make sure builds will work w/o extra steps. The included BLT is also the version used in our testing. 

You can point conduit to another BLT, using the following cmake option:

```
-DBLT_SOURCE_DIR=/path/to/blt
```

And things should work modulo BLT differences that we haven't tested.

**Comment by vsoch** [comment]
Gotcha!

So my build error was something really stupid and confusing - I had a flag erroneously twice, and removing the second one fixed it? I don't even know how that happens! Anyway - no need to build blt separately the default worked great! Thank you!
