### ISSUE TITLE
conduit_index_t and ABI Compability

### ISSUE THREAD

**Issue by FreddieWitherden** [LLNL/conduit#1059]
Currently, at compile time, Conduit enables one to have `conduit_index_t` defined as either 32- or 64-bits.  However, there does not appear to be a means of ascertaining which was selected at runtime.  Thus, given a `libconduit.so` without its associated header file it is impossible to figure out what type is expected.

This makes it difficult to use conduit at an ABI level (say from an FFI).  To this end it would be useful to have a means of determining what integer type is expected.  As an example of how this can be done, SCOTCH has a function `SCOTCH_numSizeof` which enables one to query at run-time if SCOTCH has been compiled with 32- or 64-bit integer support.  The result is returned as an `int` so there are no portability issues.  Or, better still, consign 32-bit integer support to the annals of history and only use 64-bit indexes going forwards.

**Comment by cyrush** [comment]
@FreddieWitherden  thanks, yes I understand the issue -- there is a way to ask the size of `index_t` via a `DataType::index_t()` instance but it returns the answer as an `index_t` ...

I will add a simple function that returns the size as an `int`, and think about the right name in C++ vs C.

Vast majority of Most cases folks are using 64-bit index_t. Guessing is bad practice for ABI but it would be a correct guess for most builds.

Thanks for the feedback!

**Comment by cyrush** [comment]
@FreddieWitherden I merged a PR with a function that should help with this to conduit@develop, and it will be in conduit 0.8.6 release
