### ISSUE TITLE
Possible bug in json output of empty arrays

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/conduit#1075]
I posted an issue to Axom related to sidre output for empty arrays: https://github.com/LLNL/axom/issues/1018

The problem appears to be that empty arrays produce entries with a key that's missing a value, e.g.
```
value: 
```
but should probably generate a value that has an empty array, e.g.
```
value: []
```

I don't yet have a reproducer in conduit, but I think the issue is likely in `conduit::Node::to_json_generic()`

**Comment by cyrush** [comment]
@kennyweiss  Sounds similar to the issue fixed here, https://github.com/LLNL/conduit/pull/993

What version of conduit is axom using? This fix should be in conduit 0.8.4 or newer

**Comment by kennyweiss** [comment]
Thanks -- that does look similar!

Axom's on `conduit@0.8.3` -- I'll try a newer version and see if that fixes things.

**Comment by kennyweiss** [comment]
**Update:** I built axom against `conduit@0.8.6` and verified that this bug has been resolved.

Thanks for already having a solution @cyrush !

**Comment by cyrush** [comment]
@kennyweiss glad that helped and thanks for confirming!
