### ISSUE TITLE
macOS [u]int64 mismatches

### ISSUE THREAD

**Issue by mathstuf** [LLNL/conduit#1090]
In updating Catalyst's embedded Conduit from 0.8.4 to 0.8.6, [this error](https://gitlab.kitware.com/paraview/catalyst/-/jobs/7972350#L290-L296) showed up:

```
/opt/glr/paraview/catalyst-ci/thirdparty/conduit/conduit/conduit_data_type.cpp:39:1: error: static_assert failed due to requirement 'std::is_same<long, long long>::value' "error: conduit_int64 != std::int64_t"
static_assert(std::is_same<conduit_int64, std::int64_t>::value,
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/glr/paraview/catalyst-ci/thirdparty/conduit/conduit/conduit_data_type.cpp:52:1: error: static_assert failed due to requirement 'std::is_same<unsigned long, unsigned long long>::value' "error: conduit_uint64 != std::uint64_t"
static_assert(std::is_same<conduit_uint64, std::uint64_t>::value,
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I don't see anything interesting in the diff between 0.8.4 and 0.8.6 though…

MR updating Conduit is [here](https://gitlab.kitware.com/paraview/catalyst/-/merge_requests/82/diffs).

**Comment by cyrush** [comment]
I don't think any of the type mapping logic changed between 0.8.4 and 0.8.6.

But it seems it's making a different choice about `long` vs `long long` than the compiler is making for c++ std.

Here is the output of conduit logic:

```
-- Bitwidth Mapping: preferring `long` over `long long` for c++11 compatibility
-- Bitwidth Mapping Results:
--  conduit::int8  native type: signed char
--  conduit::int16 native type: signed short
--  conduit::int32 native type: signed int
--  conduit::int64 native type: signed long
--  conduit::uint8  native type: unsigned char
--  conduit::uint16 native type: unsigned short
--  conduit::uint32 native type: unsigned int
--  conduit::uint64 native type: unsigned long
--  conduit::float32 native type: float
--  conduit::float64 native type: double
```

Could anything else have changed (compiler, c++ standard, 64-bit vs 32-bit compilation)?

**Comment by mathstuf** [comment]
Hmm…CMake was updated to 3.26.

**Comment by mathstuf** [comment]
Ok, I can't reproduce with just Conduit…something about the embedded Catalyst stuff changes things.

**Comment by mathstuf** [comment]
Ok, setting the minimum CMake to 3.26 changes some policy apparently…I'll search through those.

**Comment by mathstuf** [comment]
[CMP0126](https://cmake.org/cmake/help/latest/policy/CMP0126.html) is changing the behavior.
