### ISSUE TITLE
add option to avoid replacement to node update

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#112]
There are some situations where updating a host node with the contents of remote node is desirable without replacing existing data in the host node.  This feature would be very useful in situations where the host node has previously allocated memory as avoiding replacement would avoid unnecessary data reallocation.

@cyrush: Does this addition seem reasonable to you?  If so, do you think it would fit best as an option to the existing `conduit::Node::update` functions (e.g. `do_replace = bool`) or as some form of separate function?

**Comment by cyrush** [comment]
@xjrc you want to avoid an allocation in the case that the data is compatible with where you want to put it?

update already supports that use case

**Comment by xjrc** [comment]
Unfortunately, the data isn't always compatible in my case since the sizes of the data allocations can be different.

Essentially, I want to use `update` to fill in a Blueprint material node to ensure that it has all the appropriate fields before I start pushing data to it.  However, if this material node already has the appropriate fields, I don't want to replace their associated values.  Once I'm sure that my node has all the proper fields, I'd like to change the size of its `volume_fractions` child node to a new value if the new data it's being filled with has a different number of entries.

Thinking about this more carefully, I don't even think that `update` without replacement is what I really want.  Ideally, I'd prefer to be able to project the contents of one node onto another with exclusions (e.g. nodes with list allocations), which is essentially a more sophisticated version of `update` without replacement.  This functionality would allow me to ensure that my Blueprint material nodes have the correct structure while avoiding issues related to clobbering existing array nodes with allocation sizes that differ from my `update` template node.

This functionality seems pretty special case, but I think it could be useful for other users.  I'll just write it locally for now and we can discuss whether or not it would fit in the mainline once I finish the initial implementation.

**Comment by cyrush** [comment]
It sounds like you may be able to do what you want with a mix of set_external and various checks, but I ma not sure -- it seems a bit complex.  I suggest you take a stab at it in your code and we can try to see if there is a general pattern that emerges that would make sense to add to the conduit api.

**Comment by xjrc** [comment]
I'm not really sure what I was talking about here, but I think I was able to implement what I wanted without a special function, so I'm going to close this for now.
