### ISSUE TITLE
small error in the documentation about the mixed topologies

### ISSUE THREAD

**Issue by lucas-givord** [LLNL/conduit#1133]
Hi,

After some confusion of my part and discussion with @mennodeij. It looks like there is a small error in the doc about mixed topologies here : https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#mixed-topologies-with-shapes-shape-map

we specify  `polygon` instead of `polygonal` for the `shape_map` here:

`shape_map/polygon: (numeric entry for polygon, e.g. 7 - VTK_POLYGON)`

**Comment by cyrush** [comment]
Thank you. I merged the PR with the fix.
