### ISSUE TITLE
Partitioned mesh with matsets looks wrong.

### ISSUE THREAD

**Issue by BradWhitlock** [LLNL/conduit#1155]
I have a mesh with a matset that I'm running through conduit's partitioner. The partitioned output looks wrong in VisIt. VisIt uses the to_silo() function to turn various matset representations into Silo/VisIt-compatible material data.

**Comment by BradWhitlock** [comment]
The materials look wrong in the far domains in the partitioned mesh (right).
![partitioned_matset](https://github.com/LLNL/conduit/assets/2072964/ea38107e-30ec-4ec8-8bba-7a63f0771625)

**Comment by BradWhitlock** [comment]
On further inspection, the partitioner makes a material-dominant matset and the far domains do not have all materials defined. Their matset definition with a domain is fine. Material-dominant matsets do not tend to have a material_map node, or it is at least optional. The lack of material_map node prevents to_silo() from making the right material numbers in those domains. A solution would be to make the partitioner preserve or create a material_map node in the output matset.

**Comment by cyrush** [comment]
@JustinPrivitera  also had a puzzle related to to_silo.

I wonder if there is an indexing constraint related to numbering .

**Comment by cyrush** [comment]
Ok - that's along the lines of what we may have hit as well. 

I see you are getting to the root issue, thank you!

**Comment by BradWhitlock** [comment]
@cyrush, I'm preparing a PR that makes the partitioner output a material_map and that fixed my problem when looking at the data in VisIt.
