### ISSUE TITLE
CMakeLists.txt at root

### ISSUE THREAD

**Issue by ibaned** [LLNL/conduit#1185]
I notice your top-level `CMakeLists.txt` file is in the `src` subdirectory. We've had to add support for this in our build tool and no other project behaves this way. Could you add a `CMakeLists.txt` file at the root directory that just invokes the one in `src`?

**Comment by cyrush** [comment]
Hi @ibaned - happy to try to find a way to help with your build workflow.

Adding a simple CMakelists.txt file that includes the main one makes cmake unhappy:

```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

It also changes the full project root, which breaks some of the root relative path used across the build system. 

Any other ideas of what we can try?

**Comment by ibaned** [comment]
Ah, that's unfortunate... Even if you went through the refactoring to put those commands there and change the paths it would likely break current users who find the top-level `CMakeLists.txt` file in `src`... I suppose this is something that would be compatibility breaking so it's up to you if you want to go through the trouble. We can keep working around it, but at least if you start future projects it would be great to follow the convention of a root directory CMake file. Thanks for trying!

**Comment by cyrush** [comment]
Yes, sorry this is a pain for your team. This is a pattern we have used in a few project to clearly partition the compiled code from other revision controlled aspects of a project. If you see it pop up else where, you can shake your fist in my general direction :-)

**Comment by rhornung67** [comment]
@cyrush you'll get your comeuppance 👊
