### ISSUE TITLE
Silo root file in ParaView

### ISSUE THREAD

**Issue by ibaned** [LLNL/conduit#1191]
Hello,

When writing to Silo, Conduit generates a root file whose filename ends in `.root`. Using the latest version of ParaView, that file isn't recognized as anything that can be opened and I have to manually allow all file types and manually select the `VisItSiloReader` in order to open it. Is there a way to make the root file end in `.silo` as well?

Thanks!

**Comment by JustinPrivitera** [comment]
Yes that is possible. @cyrush can I go ahead with adding an option for this?

**Comment by cyrush** [comment]
@JustinPrivitera sure thing - let's add an option to control the root file suffix.

**Comment by ibaned** [comment]
Thank you both!

**Comment by ibaned** [comment]
somewhat unrelated question, but what is `overlink`? Is that something I need to understand when considering how to use Silo through Conduit or is it fairly special-case?

**Comment by cyrush** [comment]
@ibaned  Overlink is a general mesh overlay / linking tool used at LLNL. Overlink flavored silo files have some additional info, constraints, and requirements that build on base silo. (One example: Material Volume fractions must be present) 
So in addition to base silo, we also want to support overlink flavored silo.

**Comment by ibaned** [comment]
Thanks @cyrush ! Sounds like something I don't currently need to worry about

**Comment by ibaned** [comment]
Just to confirm, this works great for me! thanks again

**Comment by JustinPrivitera** [comment]
Glad we could help!
