### ISSUE TITLE
target MPI::MPI_CXX not found for CATALYST_WITH_EXTERNAL_CONDUIT=ON

### ISSUE THREAD

**Issue by jhgoebbert** [LLNL/conduit#1292]
When building Catalyst with `CATALYST_WITH_EXTERNAL_CONDUIT=ON` it fails with
```
CMake Error at /p/software/jsccloud/stages/2024/software/Conduit/0.9.2-gpsmpi-2023a/lib64/cmake/conduit/conduit.cmake:86 (set_target_properties):
  The link interface of target "conduit_relay" contains:

    MPI::MPI_CXX

  but the target was not found. 
[..]
```
because `conduit.cmake` includes `MPI::MPI_CXX` instead of expanding it:
```
[..]
set_target_properties(conduit_relay PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "[..]"
  INTERFACE_LINK_LIBRARIES "[..];MPI::MPI_CXX"
  INTERFACE_LINK_OPTIONS "[..]"
)
[..]
```
This inclusion of `MPI::MPI_CXX` forces all cmake-projects which use the Conduit installation to have the target `MPI::MPI_CXX` defined.
Which is not the case for example for Catalyst (even though I set `CATALYST_USE_MPI=ON`)

**Comment by cyrush** [comment]
@jhgoebbert  thanks for the report.

Conduit's libraries are partitioned to provide a set of non mpi and mpi dependent libs. 

The goal is to only use MPI when MPI APIs are being leveraged, hence the separate libraries. 

For example:
```
libconduit_relay.so
libconduit_relay_mpi.so
libconduit_relay_mpi_io.so

libconduit_blueprint.so
libconduit_blueprint_mpi.so
```

In a cmake context, we provide the conduit::conduit` and `conduit::conduit_mpi` targets to make this distinction as well. 

So why are you seeing an problem here? 
You have a problem with `libconduit_relay.so`, which is not supposed to be using MPI?

I suspect in your case you are linking against an HDF5 that is built with MPI support. 



Even though conduit relay isn't using HDF5's MPI support, having HDF5 built this way forces an MPI link dependency downstream (conduit_relay)

In Conduit, we have to detect this case and then downstream CMake users are responsible for finding MPI.

https://github.com/LLNL/conduit/blob/ad86e316ad56a75c099d30ca5ce75cff275b5924/src/libs/relay/CMakeLists.txt#L192


You may have a good reason for using HDF5 w/ MPI support -- but Conduit itself doesn't leverage it.

Ways forward:
- Skip MPI support for the HDF5 Conduit is using
- Skip buildig Conduit's HDF5 support
- Use FindMPI when using Catalyst

Let me know if you have any questions or if I can provide more info to help clarify.

**Comment by jhgoebbert** [comment]
Hi @cyrush 
thank you for the detailed answer. That helps a lot to think about the possible solutions.  

- Skipping Conduit's HDF5 support is the easiest solution and it worked just as you said.
- Catalyst uses FindMPI but it does not include the CXX components: https://gitlab.kitware.com/paraview/catalyst/-/blob/master/CMakeLists.txt#L51

**Comment by cyrush** [comment]
@jhgoebbert thanks additional info -- I will look into if we can Conduit to only look for the C-components of MPI.
