### ISSUE TITLE
conduit::Node::compare() method

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#136]
Something I (Cyrus) have wanted to do for a bit – also a request from Mark Miller:

Notes from Mark Miller:
Out of curiosity, would you be amenable to having 'diff' support added to Conduit?
Given two conduit nodes, return a bool if they are the same (by value) or different
Given two conduit nodes, return a conduit node that represents their difference
Given two conduit nodes, return a string (or send strings to a caller-specified stream) of the difference
With knobs to control exclusive/inclusive diffs, absolute/relative diff tolerances, numerical diff algorithm (some examples are in silo)?

=====

Node n;
Node other;
Node res;
n.compare(other,res)
res could contain a node that has the following sub nodes:
difference - parts of the tree that are in both "n" and "other", with leaves diffed 
missing - parts of the tree that are in "other" but not in "n"
extra - parts of the tree that are in "n" but not in "other"
Tricky things:
String diffs - how do we present them (maybe just say equal or not, keep it numeric with a lexical distance?)
Lists, with varying elements between n and other. Shouldn't be too bad, but requires some thought.
or we could go simpler, and just compare the things that are both in "n" and "other"

**Comment by xjrc** [comment]
@cyrush: I'd like to tackle implementing this feature next week so that I can use it in another application. Let me know if you have any extra ideas related to this feature and we can discuss a game plan. Thanks!

**Comment by cyrush** [comment]
@xjrc awesome! feel free to ping me with questions and we can iterate in a PR.

**Comment by cyrush** [comment]
resolved in #246
