### ISSUE TITLE
blueprint "domain_adjacencies" naming discussion

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#189]
The `domain_adjacencies` section of the Blueprint schema doesn't have the best name because it doesn't mesh well with the other section names (e.g. `coordsets`, `matsets`).  This name should be changed so that it better fits the style of the Blueprint schema and causes fewer typing headaches.

The following list enumerates some potential alternatives:
- `adjgroups`
- `adjsets`
- `abutments`
- `commgroups`
- `commsets`

Once we've decided on an adequate name, I'll revise the changes in issues #180 and #185.

**Comment by cyrush** [comment]
leaning towards `adjsets`

Thinking into the future we will need to have a name for amr nesting info `nestsets` may work and fit the existing mold.

Also wondering if we should employ snake case:

- `coord_sets`
-` mat_sets`
-` adj_sets`

**Comment by xjrc** [comment]
Fixed with upcoming changes in #185.
