### ISSUE TITLE
add "zero copy if possible" operation

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#190]
When reading in data from a Conduit node, it's common for a user to want this data to be represented using a specific data type (e.g. `int32`).  In order to support this use case, Conduit provides the `to_[type]` functions, which copy the data from the source node into a given destination node while transforming the data into the requested type.  For users that want to minimize memory usage, this solution isn't ideal as it performs a copy regardless of source/destination data compatibility.

In order to satisfy the needs of memory-concious users, a function should be added to `conduit::Node` that zero copies data if possible (i.e. the requested type matches the source node's data type) and full copies data otherwise.  While the implementation for this concept is simple, summarizing it as a function name is a bit more challenging.  The following are some potential names for this operation:

- `put_[type]`
- `fix_[type]`
- `make_[type]`
- `pass_[type]`

Once we decide on a proper name for this function, I'll work on adding it to the code.

**Comment by cyrush** [comment]
still don't think those names really convey to operation, also still not sure what to suggest :-(

**Comment by cyrush** [comment]
I think for your case you want, there are actually  two predicates for the `if`

if:
- it's the type you want
- the data is compact (thats the only way you can consume, via a compact allocation?)
- zero copy to output

otherwise:
- use to_{the type you want} 
  (this will do conversion and create a compact allocation for the result)


The fact that there are two predicates makes it even harder to name :-(

**Comment by cyrush** [comment]
Here is an example from MFEM that I think mirrors what you want:
```
   // mfem requires ints, we could have int64s, etc convert if necessary
   if (n_mesh_conn.dtype().is_int() &&
       n_mesh_conn.is_compact() )
   {
      elem_indices = n_mesh_topo["elements/connectivity"].value();
   }
   else
   {
      Node &n_mesh_conn_conv=
         n_conv["topologies"][topo_name]["elements/connectivity"];
      n_mesh_conn.to_int_array(n_mesh_conn_conv);
      elem_indices = n_mesh_conn_conv.value();
   }
```

**Comment by xjrc** [comment]
Closing this since it will likely be added as part of a more general capability if it's added at all; see #288 for relevant discussion.
