### ISSUE TITLE
Layout of field data

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#208]
I did not see this in the documentation. For example, if you have a 2D field, is x or y varying the fastest?

**Comment by cyrush** [comment]
Yes, we need to add details about this to the docs. 

For a 2D field, when associated with an implicit topology  (`uniform`, `rectilinear`, or `structured`) , the field values fast vary with `i` then `j`.

For 3D, its `i`, `j`, then `k.` 

Basically, it follows the way VTK works in these cases. 

For most cases this will also be `x,y(z)`.  But we are leaving open the possibility that say, `x` in the coord set may not be associated with the first logical dimension (`i`)

**Comment by cyrush** [comment]
I added some (very small) blurbs in #210
