### ISSUE TITLE
serializing and reading back a node structure multiple times does not work

### ISSUE THREAD

**Issue by tomvierjahn** [LLNL/conduit#226]
* Storing the schema and serializing a node in order to afterwards do `second_node.set_data_using_schema(...)`
works.
* However, immediately storing its schema and serializing it in order to afterwards do `third_node.set_data_using_schema(...)`
does not work.

What am I missing?

See `src/tests/t_conduit_serialize_read_multiple_times.cpp` in branch `#226_serializing_and_reading_back` in my fork [here](https://github.com/tomvierjahn/conduit/tree/%23226_serializing_and_reading_back).

**Comment by cyrush** [comment]
@tomvierjahn thanks for the detailed examples, I'll take a look early next week (11/26)

**Comment by tomvierjahn** [comment]
The second serialization writes incorrect data if the node is not copied after reading. I have made the test more detailed in this regard.

**Comment by cyrush** [comment]
@tomvierjahn, I found the issue -- for compact data, the offset wasn't being used for that path in `serialize`.

PR #229 contains the fix and a simple test, based those in your fork.

**Comment by cyrush** [comment]
@tomvierjahn master should include the fix, let me know if you hit any issues.

**Comment by tomvierjahn** [comment]
@cyrush, I removed the copying in my code. It now works as intended using conduit’s master.
Thanks for the quick fix.

**Comment by cyrush** [comment]
@tomvierjahn, great -- thanks for verifying the fix!
