### ISSUE TITLE
Copying/assigning nodes does not preserve a nodes's externalness

### ISSUE THREAD

**Issue by tomvierjahn** [LLNL/conduit#228]
Given a `Node` w/ external data.

When I copy the node or assign it to another node and then change the raw external data, I would expect the copied/assigned node to reflect that change.

Turns out, it does not. Is this intentional?

Using `set_external` in order to let this node also reflect the changes made to external data. This is inconvenient. Once I have the external node I do not want to keep track of it being external, anymore.

See  #src/tests/t_conduit_node_copy_external.cpp in branch #228_copying_assigning-nodes-does-not-preserve-a-nodes's-externalness in my fork [here](https://github.com/tomvierjahn/conduit/tree/%23228_copying_assigning-nodes-does-not-preserve-a-nodes's-externalness).

**Comment by cyrush** [comment]
@tomvierjahn This is intended, we decided to make copy assign have the same semantics as `set`. 

You do need to use `set_external` to get the shallow copy behavior.

We wanted folks to be explicit with using `set_external`, so folks don't accidentally modify things via shallow copies.

**Comment by tomvierjahn** [comment]
Fair enough. Then I can design around that, accordingly.
@cyrush, thank you for clarifying.

Closing the issue.
