### ISSUE TITLE
Node using external node's data does not reflect updates

### ISSUE THREAD

**Issue by tomvierjahn** [LLNL/conduit#240]
I am trying to communicate data between nodes and would like to use `set_external` for this purpose:
```c++
conduit::Node original_node;
conduit::Node referring_node;
referring_node.set_external(original_node);
```

However, changes to one node are not reflected by the other. Is this intentional?

See [`t_conduit_node_external_reflect_changes.cpp`](https://github.com/tomvierjahn/conduit/blob/%23240_Node_using_external_nodes_data_does_not_reflect_changes/src/tests/conduit/t_conduit_node_external_reflect_changes.cpp) in `240_Node_using_external_nodes_data_does_not_reflect_changes` of [my fork](https://github.com/tomvierjahn/conduit/tree/%23240_Node_using_external_nodes_data_does_not_reflect_changes) for an example.

**Comment by cyrush** [comment]
@tomvierjahn, any data values changes will be reflected -- but the if the structure of the node changes (read, its schema changes) those changes won't be reflected. 

Restated:  They aren't that tightly coupled -- the objects aren't shallow copies of each other, but they can reference the same data.

**Comment by tomvierjahn** [comment]
@cyrush, thanks for your clarification. I will be using `Node*` then.
