### ISSUE TITLE
cull empty slashes in fetches

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#243]
Paths with extra slashes cause issues:

`n["//a"]= 10`

currently creates something like

`{ "" : { "": { "a" : 10 } }`

To be more robust, I think it should be have more like file system paths, which are more forgiving:

For example:

`n["//a"]= 10`

would create:

`{ "a" : 10 }`

**Comment by cyrush** [comment]
@bryujin does this sound sensible to you?

**Comment by bryujin** [comment]
I'm OK with it being more file system path-like as long as it's clearly documented on what it does. I trying to think of a good reason to have empty string named nodes, but I'm not really seeing it at the moment. 
Do we ever use or intend to have some sort of absolute path mechanics? That's the only dangerous part I can see about stripping them now, but those don't seem to really fit the model that we currently have.

**Comment by cyrush** [comment]
@bryujin thanks!

This undermined me when dealing with some auto generated path strings, which I think its going to a be a more common occurrence (and headache) than any potential good use case for objects with children named "". 

I don't know of any compelling any use cases for abs path - we could make the semantics make sense but seems like a stretch. If we do wanted to do so in the future -- we could still provide abs path while skipping duplicates, but I am not going to address that now.
