### ISSUE TITLE
blueprint:  nestsets proposal for structured AMR

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#255]
A proposal for nestsets to hold information about the nesting of domains on different adaptive mesh refinement levels.  A domain would hold an object called _nestsets_, containing an object for every other domain nested by or nested in this domain.

nestsets/nestset/parent: domain id of parent  (coarser)
nestsets/nestset/child: domain id of child  (finer)   ! only one of parent or child will be used
nestsets/nestset/ratio: {n,n,n}   ! refinement ratio between the domains
nestsets/nestset/association: “vertex” | “element”  ! Overlaps refer to vertex or element centering
nestsets/nestset/overlap/local: {i0,j0,k0},{in,jn,kn}  ! index coordinates of local overlapped region
nestsets/nestset/overlap/remote: {i0,j0,k0},{in,jn,kn}  ! index coordinates of remote overlapped region

**Comment by cyrush** [comment]
@nselliott thanks for adding!

**Comment by cyrush** [comment]
to close this one out, we really need a blueprint example. 

My plan has been to do an AMR extension to the julia example, but I haven't had the free cycles to implement it.

**Comment by cyrush** [comment]
resolved with new julia amr examples
