### ISSUE TITLE
to_multi_domain doesn't check if single domain is valid

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#274]
Calling `to_multi_domain` checks to see of if the node is a valid multi-domain, and if it is not, then it creates a new node and appends whatever was passed in to the new node. However, it does not check to see if the node was a valid single domain. On the next call to `to_multi-domain`, it will fail the verify multi-domain call since it was not a valid single domain in the first place, and the input node will get appended again.

I am not sure if the caller should be responsible for checking to see if the input is valid on the first place before calling `to_multi_domain`.

**Comment by mclarsen** [comment]
I would suggest checking to see if the input was valid, and returning false if the conversion was successful rather than always returning true.

**Comment by cyrush** [comment]
these methods assume verify is true, that said always returning true in the manner that is currently there seems bad

**Comment by cyrush** [comment]
closing since we expect only to call when verify is true and that is pseudo documented. 
I think the implementation is reasonable given the pre-condition that input is mesh-bp conforming.
