### ISSUE TITLE
mesh bp: allow implicit points topology

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#287]
make it easy to define a topology that uses all points in a coordinate set.

**Comment by gzagaris** [comment]
@cyrush is this relating to particle meshes at all? i.e., store particle meshes with an explicit coordset and add a topology type that indicates that this is an "implicit point" topology?

**Comment by cyrush** [comment]
@gzagaris, yes, exactly like we talked about. This came up again in another context.

**Comment by gzagaris** [comment]
Great! Looking forward to this. We are already doing this in Mint, so, we can take this for a spin when you're ready.
