### ISSUE TITLE
conduit spack packages does not respect ~shared

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#294]
Conduit spack package does not respect `~shared`. Conduit is configured by the host config file it generates and omits any references to shared libs. The line: 
`if "~shared" in spec: 
    cfg.write(cmake_cache_entry("BUILD_SHARED_LIBS", "OFF")`

Note: I was bit by the `ENABLE_SHARED` versus `BUILD_SHARED_LIBS` yet again.

**Comment by cyrush** [comment]
this is resolved in spack develop and in the ascent spack fork
