### ISSUE TITLE
update conduit's ver of blt

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#296]

**Comment by kennyweiss** [comment]
This line needs to be commented out 
https://github.com/LLNL/conduit/blob/4d53d6bcd0ce3b6c8773fc6f0af3c012c7e3f643/src/CMakeLists.txt#L93
since ``ENABLE_SHARED_LIBS`` is now deprecated.

**Comment by cyrush** [comment]
thanks @kennyweiss  -- does it cause an error if it's still there? Want to make sure I test for problems folks tripped on. 

(Conduit always used BUILD_SHARED_LIBS instead of ENABLE_SHARED_LIBS)

**Comment by kennyweiss** [comment]
Yes -- it is now a fatal error if ``ENABLE_SHARED_LIBS`` is defined.

https://github.com/LLNL/blt/blob/d298777de4f95db9201ba18d7443fff48d2b9867/cmake/BLTOptions.cmake#L148-L151

**Comment by cyrush** [comment]
great, thanks!

**Comment by cyrush** [comment]
resolved in #298
