### ISSUE TITLE
make dedicated blueprint examples for new users

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#297]
There should be a dedicated set of Blueprint examples targeted at acquainting new users to the format. These examples should be tested like all of the other existing examples while facilitating trivial comparison between a Blueprint node and what it represents. This task can be accomplished by enhancing the [`t_conduit_docs_blueprint_examples.cpp`](https://github.com/LLNL/conduit/blob/master/src/tests/docs/t_conduit_docs_blueprint_examples.cpp) file and its associated documentation.

**Comment by wnissen** [comment]
I would love this, I was just looking at the braid example and wishing it was in Python. I think it would easily fit in a single file.

**Comment by xjrc** [comment]
These new examples have been added with the merging of #311.
