### ISSUE TITLE
should all implicit topologies support dims?

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#303]
While working on #197, I noticed that the [Blueprint documentation](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#implicit-topology) defines the schemas for each of the implicit topologies as follows:

- **points**: An implicit topology using all of the points in a coordinate set.
  - topologies/topo/coordset: “coords”
  - topologies/topo/type: “points”
- **uniform**: An implicit topology that defines a grid of elements on top of a uniform coordinate set.
  - topologies/topo/coordset: “coords”
  - topologies/topo/type: “uniform”
  - topologies/topo/elements/origin/{i0,j0,k0} (optional, default = {0,0,0})
- **rectilinear**: An implicit topology that defines a grid of elements on top of a rectilinear coordinate set.
  - topologies/topo/coordset: “coords”
  - topologies/topo/type: “rectilinear”
  - topologies/topo/elements/origin/{i0,j0,k0} (optional, default = {0,0,0})
- **structured**: An implicit topology that defines a grid of elements on top of an explicit coordinate set.
  - topologies/topo/coordset: “coords”
  - topologies/topo/type = “structured”
  - topologies/topo/elements/dims/{i,j,k}
  - topologies/topo/elements/origin/{i0,j0,k0} (optional, default = {0,0,0})

I find it a bit peculiar that the `structured` type is the only one to support defining a topology in terms of extents in a potentially larger coordinate set. It seems to me like `uniform` and `rectilinear` have half the support for this feature by including the optional `origin` parameter, but they both need the `dims` parameter for the full flexibility in describing extents like `structured` has.

With all of this being said, I have two questions:
- Should `dims` be added as a parameter for the `uniform` and `rectilinear` topology types?
- Should `dims` be made optional in all places and default to the full dimensions of the underlying coordinate set (similar to how this field is handled for [child nodes in `nestsets`](https://github.com/LLNL/conduit/pull/285))?

**Comment by nselliott** [comment]
@xjrc Is it that uniform and rectilinear are assumed to have a 1-to-1 mapping with the coordset, but structured might only cover part of the coordset?

**Comment by xjrc** [comment]
@nselliott: That may have been the original idea, but that doesn't explain why those two types allow logical `origin` values. Even regardless of that, I don't see why `structured` should be the only one of the implicit topologies to support partial covering. From my perspective, if we support that feature for one of the types, we might as well do it for all of them.

**Comment by nselliott** [comment]
@xjrc Having **origin** and **dims** in the topologies makes sense to me, though I think they should be optional, since they can be redundant with information available in the coordset, particularly when there is a 1-to-1 mapping.

**Comment by xjrc** [comment]
I got clarification on @cyrush on what the `origin` value actually means for implicit topologies and it seems as though its intended use is not to allow `coordset` subsetting, but rather to facilitate index offsets for global indexing. I'll update the documentation to make the intent of this variable more clear.
