### ISSUE TITLE
braid mesh examples inconsistent handling of 2D meshes

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#332]
Element centered handling of z = 0:
https://github.com/LLNL/conduit/blob/5d9abab816dc6359d16237345036cd2160e611c7/src/libs/blueprint/conduit_blueprint_mesh_examples.cpp#L281

everything else is nx * ny *nz and ends up being an empty field. Passes verify as well.

**Comment by cyrush** [comment]
Resolved in #335
