### ISSUE TITLE
Blueprint vector data naming conventions

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#336]
The braid vector data examples use `{u,v,w}` names for each component, but in the mcarray documentation, `{x,yz}` is used. Is the "official" vector data naming convention `{u,v,w}`?

**Comment by cyrush** [comment]
To answer the first q, there isn't an official naming convention -- the component names are free just like the field names. That said, when plotting the 3D vectors we do have an implicit expectation that the first component is tied to the first coord in the coord system, second to the second, etc.

**Comment by cyrush** [comment]
checked the docs, and the array of structs vs struct of arrays seems resolved.
