### ISSUE TITLE
Blueprint index generation is missing state fields

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/conduit#353]
Per the [user docs](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#state), the following (optional) "state" metadata are part of the blueprint:
* state/time
* state/cycle
* state/domain_id

When present, these fields should also be copied over to the blueprint index in ``conduit_mesh_blueprint::generate_index()``.

**Comment by cyrush** [comment]
@kennyweiss @mclarsen added logic to propgate the cycle and time when present to the blueprint index in PR #386
