### ISSUE TITLE
adjsets domain-level neighbor information for structured domains

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#354]
For structured meshes, it would be good to have an option in adjsets to store neighbor information without needing to use the current element-based format.  In some cases, an option to simply identify a pair of domains as being adjacent would be sufficient without any other information.  Options to describe more specifically how two domains are adjacent would be needed for more general cases--which face/edge/corner touches the adjacent domain, and do the domains have different axis orientations?  I'll come back with some specific suggestions.

**Comment by nselliott** [comment]
First suggestion, for cases where we only want to identify that domains are adjacent without any further information:

Currently we have 

```
adjsets/adjset/association: “vertex” | “element”
```

I propose adding "neighbors" as another valid keyword here.

```
adjsets/adjset/association: “vertex” | “element” | "neighbors"
```

```
adjsets/adjset/association: "neighbors"
              /topology: "topo"
              /group/neighbors: (integer array)
              /group/values: not used
```

The group/neighbors integer array could be all of the domain IDs for domains touching a single shared domain boundary, or it could be a pair of IDs, with an adjset entry for every pair of adjacent domains.

Other suggestions for the new association keyword are welcome.  I thought of "domains" or "idarray".

**Comment by nselliott** [comment]
For more general cases, we need information about how the domains touch and possibly axis orientation information.  I think this must be restricted to an adjset entry for every pair of domains.


```
adjsets/adjset/association: "boundary"
              /topology: "topo"
              /group/neighbors: (integer array) (pair of domain IDs)
                    /values: not used
                    /boundary: "face" | "edge" | "corner"
                    /location: (integer array)
                    /orientation: (integer array) (optional)
```

The location is a logical identifier of which face/edge/corner is being described here.  2D domains have 4 edges/4 corners.  3D domains have 6 faces/12 edges/8 corners.

The orientation is a 3-integer description of one domain's axes in terms of the other's.  If not present, the default assumption would be that both domains have the same orientation.

**Comment by nselliott** [comment]
@cyrush @bryujin @xjrc Let me know if you have any comments.

**Comment by cyrush** [comment]
@nselliott  Thanks! I The association is for what part of the topology it the adjset refers to - so I think that part would stick with vertex or element, however we do need to encode that info.

**Comment by nselliott** [comment]
@cyrush OK, though in these cases we don't need to identify vertex/element, so we could leave off the association and create something new to identify these adjacencies.

**Comment by cyrush** [comment]
we still need to know if they logical windows are vertex-based or element-based (much like the current adjsets, even though in practice we only currently use one of them) -- does that make sense?

**Comment by nselliott** [comment]
My proposals here don't use logical windows, though I suppose we could call them vertex since they're implicitly referring to where vertices are shared.

**Comment by cyrush** [comment]
@nselliott , sorry I need to read more -- moving too fast. I'll try set aside a window a bit latter this week.

**Comment by nselliott** [comment]
We could use "vertex" as the association and then the presence or absence of certain child nodes could distinguish that we're using these new types of adjsets.

The first suggestion is distinguished by the presence of group/neighbors and absence of group/values.

```
adjsets/adjset/association: "vertex"
              /topology: "topo"
              /group/neighbors: (integer array)
                    /values: not used
```

The second is similar but has further entries for boundary/location/orientation.

```
adjsets/adjset/association: "vertex"
              /topology: "topo"
              /group/neighbors: (integer array)
                    /values: not used
                    /boundary
                    /location
                    /orientation
```

**Comment by nselliott** [comment]
Correcting the above to more closely match current adjset format:

```
adjsets/adjset/association: "vertex"
              /topology: "topo"
              /groups/group/neighbors: (integer array)
                           /values: not used
```

```
adjsets/adjset/association: "vertex"
              /topology: "topo"
              /groups/group/neighbors: (integer array)
                           /values: not used
                           /boundary
                           /location
                           /orientation
```

**Comment by cyrush** [comment]
@nselliott sorry I haven't been able to dive deep on this yet. 

One concern I have is that this will introduce the concepts of "face" "edge" and "corner".

What do those mean, and how are they related to the topology? One reason why they aren't there yet is b/c using them gets in to combinatorial differences between codes. Its quite hard to do right, we have actively avoided trying to capture them. 

For the unstructured stuff, we simply specify which vertices are adjacent.  For this I envision basically the same thing, however using logical windows for that link either vertices or elements between domains. Similar to the decomp pack format convented used in silo. 

Can you sync up with @ryujin1 to chat about this?

**Comment by nselliott** [comment]
@cyrush understood, what about something like this?

```
adjsets/adjset/association: "vertex"
              /topology: "topo"
              /groups/group/neighbors: (integer array pair of domain ids) {a, b}
                           /windows/window_a/origin {i,j,k}
                                            /dims {i,j,k}
                                   /window_b/origin {i,j,k}
                                            /dims {i,j,k}
                           /orientation
```

**Comment by cyrush** [comment]
@nselliott -- yes thats more along the lines of what I had in mind.

**Comment by bryujin** [comment]
Is the intention here to have it mirror to some extent what was done in the Silo Multimeshadjacency? This looks pretty similar, and we do know that it is sufficient information for what we need to do.

**Comment by cyrush** [comment]
@bryujin yes, I think its fair to say that should be a source of inspiration, also the decomp-pack data structure

**Comment by bryujin** [comment]
It looks pretty similar with the additional origin data, so it seems reasonable. Orientation is going to be interesting to try to explain.

**Comment by cyrush** [comment]
@nselliott i think to finish hashing this out we will need to generate example datasets

I still need to do so for the amr data, if you want to try to tackle for this case that would be great.

**Comment by nselliott** [comment]
@cyrush  I should be able to use SAMRAI to produce a json dataset.  Is that the kind of thing you're looking for?

**Comment by cyrush** [comment]
that would be a good start, and could help us converge. 

At the end of the day, I think we still want want something in the mesh blueprint examples, and something that tests the verify, etc.

**Comment by nselliott** [comment]
At the very least it would be something to look at while trying to write example code that builds the mesh out of nothing.

**Comment by cyrush** [comment]
@nselliott  -- I think we accomplished this?

**Comment by nselliott** [comment]
Yes, this has been there for a while.

**Comment by cyrush** [comment]
thanks @nselliott
