### ISSUE TITLE
Build system does not handle transitive dependencies of (static) hdf5

### ISSUE THREAD

**Issue by benson31** [LLNL/conduit#355]
Our application, apparently, requires that HDF5 is built with ZLIB support. However, when HDF5 has been built as a static library (e.g., `cmake -DBUILD_SHARED_LIBS=OFF ...`), this condition is considered neither by CONDUIT's `SetupHDF5.cmake` nor by CMake's `FindHDF5.cmake` module. Thus, there are missing symbols when various CONDUIT targets are linked. It also seems that CMake's `FindHDF5.cmake` does not explicitly acknowledge the `IMPORTED` targets created by `hdf5-config.cmake`. Linking to those (e.g. `hdf5::hdf5-static`) instead of the raw libraries seems to resolve this issue, at least on my system.

At least with a sensibly located ZLIB, there is no issue with a shared library build of HDF5 and subsequent shared library build of CONDUIT. I have not tried a crazily prefixed version to check that HDF5 actually gets its RPATH set correctly or if it just gets lucky with `/usr/lib64`.

**Comment by cyrush** [comment]
@benson31 thanks for the feedback.

Our current common downstream users don't build HDF5 with CMake.  I wouldn't expect FindHDF5 to be able to create proper imported targets for this case, although it would be nice if it worked for your case -- where HDF5 was built with CMake, but that doesn't seem to be the case.  

In my experience,  down stream users provide logic in their build system to detect and setup HDF5. Folks using CMake call FindHDF5 themselves, etc.  Not quite sure if that would work in a Super Build b/c I am not an expert there. 
  
We also most often build shared. For the shared case, we use spack so the rpaths are solid (again not building HDF5 withCMake)

**Comment by benson31** [comment]
@cyrush Thanks for the reply. That's fair. My main gripe is with CMake here, since they explicitly say the `FindHDF5.cmake` module will look for `hdf5-config.cmake` unless you tell it not to... You'd think it wouldn't be tooooooo much effort on top of that to just add a few `IMPORTED` targets. It seems at least some packages that support both a config file and a CMake-shipped module file make them interoperable with respect to `IMPORTED` targets (e.g., protobuf), but HDF5 seems to be not hopping on that bandwagon yet. That's too bad.

But anyway, with respect to our project, we're good just using the shared libraries. This was mostly just an FYI in case there are folks in the world who prefer static linkage...

**Comment by cyrush** [comment]
@benson31 we recently updated the hdf5 logic in our exported package to smooth this over now, solving cases downstream users of our static libs. So things should be resolved, if you get a chance to try and hit issues let me know.
