### ISSUE TITLE
fix coverage checks for the repository

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#412]
While browsing the results of the regression tests for my most recent branch integration, I noticed that the coverage checks hadn't been properly updated. In fact, based on the [Coveralls website](https://coveralls.io/github/LLNL/conduit?branch=master) it appears as though the coverage checks haven't been operational since January of this year. This should be fixed so that test coverage continues to be monitored for incoming changes.

**Comment by cyrush** [comment]
@xjrc, yes, the have been off for quite some time. 

When I migrated how the TPLs were build a while back I didn't work back in the pip install for the coveralls package. I got twisted on the right way to do this (which python to install to), but actually the solution is straight forward, I think we can install to the system python .

Thanks for bringing this up, I'll try to address soon.

**Comment by cyrush** [comment]
@xjrc i resolved this in #414, new branches should again pick up testing

**Comment by xjrc** [comment]
Grand, thank you!
