### ISSUE TITLE
possible typo in docs

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#417]
From the poly mesh bp docs:

"While the polygonal and polyhedral topology shape types share the same structural specification as all the the` implicit topology` shape types"

I think this should should be `explicit topology`?

**Comment by cyrush** [comment]
@xjrc I think this is a typo, I have been wanting to ask you just to make sure -- can you scan quickly?

**Comment by xjrc** [comment]
Yes, I believe that this is a typo; the *topology* for the shape types in question is *explicit*, but the *connectivity/shape index* is *implicit*. I've been doing a lot of waiting for builds this afternoon, so I'll give this section of the documentation a tune-up to better clarify the meaning of "shape types" here and I'll submit a corresponding PR. Thanks for the heads up on this!

**Comment by cyrush** [comment]
resolved in #453
