### ISSUE TITLE
conduit::relay::mpi::broadcast_using_schema segfaults when receiving nodes are not empty

### ISSUE THREAD

**Issue by ajkunen** [LLNL/conduit#418]
In the case of:

`conduit::relay::mpi::broadcast_using_schema(node, root_rank, m_comm);`

If the receiving ranks' nodes are not completely empty, this will segfault on those ranks.

This occurs with the 0.4.0 release

**Comment by cyrush** [comment]
@ajkunen 
poking at this, I think it may actually be a bug with Schema::compatible()

Working on tracking down  ...

**Comment by cyrush** [comment]
@ajkunen should be resolved on master (fix in PR #419)
