### ISSUE TITLE
Suspected yaml ambiguity between boolean and string

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#443]
In Ascent:
```
web:
  stream: "true"
```
yields:
```
  "web": 
  {
    "stream": 1
  } 
```

which is not the expected data type. I am guessing this a problem not just in the `ascent_options.yaml`

**Comment by mclarsen** [comment]
I suspect that there is ambiguity between strings that happen to be booleans and booleans.

**Comment by cyrush** [comment]
thanks for tracking this down, I was wondering what causing this error in ascent. 

In JSON we know the difference between `"true" `and `true`, given explicit quoting of strings being part of the JSON spec. In yaml, we don't know. 

Given this experience, it seems I we should simply keep `true` and `false` as strings when parsing YAML to avoid more surprises.
