### ISSUE TITLE
Mixed topology meshes fail in conduit::relay::io_blueprint::save

### ISSUE THREAD

**Issue by jedbrown** [LLNL/conduit#464]
With v0.5 (63ef74f5387706801aec2ccb0db00cb3571f32d9),
```cxx
conduit::blueprint::mesh::examples::braid("quads_and_tris", 3, 3, 0, mesh);
conduit::relay::io_blueprint::save(mesh, "foo.blueprint_root");
```
fails with
```
[/path/to/conduit/src/libs/relay/conduit_relay_io_blueprint.cpp : 210]
 No valid domains in given Blueprint mesh: Skipping save of mesh to path foo.blueprint_root
```
It works fine if I replace `"quads_and_tris"` with `"quads"`. Same problem with `"quads_and_tris_offsets"`.

**Comment by cyrush** [comment]
@jedbrown  thanks for the report, the `quads_and_tris` example uses a stream_id encoding concept that we  haven't solidified yet, still experimental. 

We should convert this example to use a simpler path -- (connectivity with set of quads then a set o tris)

Are are interested specifically in mixed-element topologies?

**Comment by jedbrown** [comment]
Yes, I would like to support mixed topology and mixed order (p-refinement), but I can make do with homogeneous for the time being.

I talked with @mclarsen a couple months ago at the CEED meeting and finally got back to adding Conduit support to PETSc. PETSc's mesh tools support mixed topology so I was hoping that my implementation could be feature-complete, but I can wait for that or take a different strategy. (A better error message would have been helpful.)  What are your plans regarding high order elements? Matt showed me an example MFEM high-order file, but the FE spaces and dof numbering is tightly tied to MFEM and not documented except via the MFEM source. He said we could propose Blueprint extensions to generalize, and we discussed a possible approach. If these mixed topology schemas are still experimental, do you (@cyrush) have a vision for high order element support?

**Comment by cyrush** [comment]
You are correct that currently mfem is the focus and it's a bit opaque -- success requires MFEM to interpret the data.  To generalize, I am all for working together to create maps that encode dof high-order relationships (element to face, to edge, etc) and whatever else is needed (winding).

**Comment by jedbrown** [comment]
Okay, thanks. I'll make a new issue for high order when ready. Regarding mixed topology, is there an example I should look at for a schema that is supported now?

**Comment by cyrush** [comment]
I don't have a simple example handy, I'll try to carve out some time to add one

**Comment by mclarsen** [comment]
Just saw this. I'm defiantly interested in understanding the dof numbering conventions so we can support high order "natively" in blueprint, i.e., something beyond MFEM specific. As I mentioned back at the CEED meeting, i'm willing to devote some time to this.

**Comment by cyrush** [comment]
Mesh blueprint now has mixed topology support from #980 and #977
