### ISSUE TITLE
Minimum CMake required is 3.9 with the use of NATIVE_COMMAND

### ISSUE THREAD

**Issue by David-Camp** [LLNL/conduit#471]
Hello,

You need to update the CMake required version to 3.9 because in cmake/thirdparty/SetupHDF5.cmake line 230, you use separate_arguments with the NATIVE_COMMAND argument. This was not supported until 3.9.
Right now it is cmake_minimum_required(VERSION 3.0) in Conduit/src/CMakeLists.txt

David Camp

**Comment by cyrush** [comment]
thanks for the report david!

**Comment by cyrush** [comment]
resolved in #475
