### ISSUE TITLE
unsupported data types (tuple)

### ISSUE THREAD

**Issue by ben-bay** [LLNL/conduit#473]
Is there a reason that Conduit nodes can't pack tuples in python?

`Exception: ('Unable to pack ', (6.746414238367816, 9.102821015130402))`

**Comment by cyrush** [comment]
@ben-bay 
can you share a bit more code, are you doing

n["value"] = (6.746414238367816, 9.102821015130402)

What version are you using?

Support for this was recently added (~0.5.0), but in this case conduit will hold as a numeric array.

**Comment by cyrush** [comment]
@ben-bay mystery solved?  Was the issue an older conduit version (just curious) ?

**Comment by ben-bay** [comment]
I think so. Is there a way within the package to check the version?

**Comment by cyrush** [comment]
conduit.about() reports version among other things. Note 0.4.1 was never released -  if you see that you are using something between 0.4.0 and 0.5.0




On November 18, 2019 at 10:51:54 AM MST, Benjamin Bay <notifications@github.com> wrote:

I think so. Is there a way within the package to check the version?
