### ISSUE TITLE
Better formatted error messages

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#477]
![Screen Shot 2019-12-17 at 9 57 03 AM](https://user-images.githubusercontent.com/4038129/71021733-ce43b500-20b3-11ea-9069-39cd39b62014.png)

**Comment by mclarsen** [comment]
its like where is waldo.

**Comment by cyrush** [comment]
great books by the way

**Comment by rhornung67** [comment]
This is the best issue posted to GitHub ever!! 🥇

**Comment by mclarsen** [comment]
<img width="885" alt="Screen Shot 2019-12-17 at 4 09 33 PM" src="https://user-images.githubusercontent.com/4038129/71044838-ac642580-20e7-11ea-8fa5-6351e6ef48bd.png">

**Comment by mclarsen** [comment]
Don't judge my artwork. I allotted 30 seconds to this.

**Comment by cyrush** [comment]
Yes: I need to improve the error output string, there is not much value in printing stringed re-jsoned details.

This can also help: 

https://github.com/LLNL/conduit/pull/424

Joe is working on helpers that filter blueprint style output logs to just show the invalid, or valid parts, etc.

**Comment by mclarsen** [comment]
Should we have a helper method that replaces the \n's with real '\n' or is there another path?
