### ISSUE TITLE
Should this be the file path separator?

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#540]
https://github.com/LLNL/conduit/blob/ec67a2ef64a00feb74ddfa8480b4421cf8f577dc/src/libs/conduit/conduit_utils.cpp#L310

**Comment by mclarsen** [comment]
There are a couple more hardcoded forward slashes.

**Comment by cyrush** [comment]
in the utils, there is a distinction between `split_path` and `split_file_path`

`split_path` should be used for conduit paths (aka '/') and `split_file_path` should be used for file system paths, it has the logic to do the right thing (linux vs windows)
