### ISSUE TITLE
bp structured indirection array

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#550]
Need a larger conversation, but from an initial conversation with @bryujin @mclarsen 

To support complex striding and fake vertex cases to zero copy structure grids, explore presenting a index arrays that apply to access coords and fields (really just an indexing array for vertices and elements)

**Comment by cyrush** [comment]
@xjrc @nselliott -- it would be good to sync up with you for a broader conversation

**Comment by gzagaris** [comment]
@cyrush (et. al) -- I don't think you need an "indirection array". 

I think what you need are:

-  the strides along each dimension, `jp` and `kp` that the code is using to map from a structured logical index space, i.e., `i,j,k` to the flat index space.
- the "real" and "whole" extent of each domain

I think this also relates to #329

Just my 2c.

**Comment by cyrush** [comment]
@gzagaris -- we discussed that option as well -- index arrays are preferable b/c they provide a general solution (beyond structured grids) as well, but we can revisit.

**Comment by gzagaris** [comment]
> @gzagaris -- we discussed that option as well -- index arrays are preferable b/c they provide a general solution (beyond structured grids) as well, but we can revisit.

Sure, but wouldn't that then mean that the mesh is no longer "structured" ?

This would be fine if the downstream application that consumes this can operate on unstructured meshes and does not care, but, it would be problematic if downstream we are expecting a structured mesh e.g., to apply a stencil operation etc. 

I could be misunderstanding what you mean by "index arrays". I take it to mean the cell connectivity. Forgive me if I am not understanding exactly what you mean here.

**Comment by cyrush** [comment]
it's not the connectivity - it's a ragged relationship between the fields and the structure of the topo. The goal is to have a little more flexibility to enable more zero copy of field data (the bulk of the data) and avoid copies but providing an indirection array.

Details will come from future discussions.

**Comment by nselliott** [comment]
@cyrush Sorry I missed noticing this discussion.  If we use a full indirection array that is good to provide generality.  It would also be nice to have a tool to generate the array automatically for the more common use cases.

**Comment by cyrush** [comment]
closing, since we are actually going to support this with nd extensions (strides, etc)

see: #926
