### ISSUE TITLE
relay::blueprint::save_mesh in lieu of relay::io_blueprint::save?

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#559]
@xjrc not sure if I ran this by you yet, but I am thinking we could deprecate:

`relay::io_blueprint::save`

in favor of something like:

`relay::blueprint::save_mesh`

I recall the reason for `io_blueprint` was to avoid confusing issues when using the namespaces (we don't want `relay::blueprint::save` and `relay::save` to be ambiguous -- I think   `relay::blueprint::save_mesh` strikes a better balance. What do you think?

**Comment by xjrc** [comment]
Approved!

**Comment by cyrush** [comment]
Cool thanks! I'll tackle this in the near future + leave the current there as deprecated between 0.6.0 and 0.7.0

**Comment by cyrush** [comment]
resolved in #588
