### ISSUE TITLE
add iterator support for `o2mrelation` structures

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#565]
In order to simplify the process of iterating over `o2mrelation`-compliant schemas, Conduit should be extended on include an `o2mrelation`-aware iterator type. This iterator should have the same general interface as `conduit::NodeIterator` with modifications tailored to `o2mrelation` fields and use cases. More concretely, the interface should look something like the following:

#### Example Interface ####

```
enum IndexType:
  DATA
  ONE
  MANY

class O2MIterator:
  // values/properties
  index_t index(IndexType itype);
  index_t elements(IndexType itype);

  // forward iteration
  bool has_next(IndexType itype);
  index_t next(IndexType itype);
  index_t peek_next(IndexType itype);
  void to_front(IndexType itype);

  // backward iteration
  bool has_previous(IndexType itype);
  index_t previous(IndexType itype);
  index_t peek_previous(IndexType itype);
  void to_back(IndexType itype);

  // human-readable information
  void info(Node& res)
```

To demonstrate the utility of this interface, here's a simple example of using it to iterate over a non-trivial `o2mrelation`:

#### Example Data ####

```
o2m:
  data: [1.0, -1.0, 2.0, 3.0, -1.0, 4.0, 5.0, 6.0]
  indices: [0, 2, 3, 5, 6, 7]
  sizes: [1, 2, 3]
  offsets: [0, 1, 3]
```

#### Example Iteration ####

```
Node o2m = /* fill in 'o2m' as above */
O2MIterator o2m_iter(o2m);

// calculate averages of each data collection
float64_array o2m_data = o2m["data"].as_double_array();
std::vector<double> o2m_avgs(o2m_iter.elements(IndexType::ONE), 0.0);
while(o2m_iter.has_next())
{
    o2m_iter.next();
    o2m_avgs[o2m_iter.index(IndexType::ONE)] += o2m_data[o2m_iter.index(IndexType::DATA)];
    if(!o2m_iter.has_next(IndexType::MANY))
    {
        o2m_avgs[o2m_iter.index(IndexType::ONE)] /= o2m_iter.elements(IndexType::MANY);
    }
}

// { 1.0, 2.5, 5.0 }
std::cout << o2m_avgs << std::endl;
```

**Comment by cyrush** [comment]
this looks good, I want to ponder a bit about the interface that implies .next() is always increments from the context of the many relationship, vs a two level scheme.

**Comment by xjrc** [comment]
I've updated this issue to reflect the preliminary interface implemented in #566.

**Comment by xjrc** [comment]
Essentially, `index(IndexType::DATA)` is the current index in the context of the `o2mrelation`'s data array and `index(IndexType::MANY)` is the current index in the context of the current set of many. To illustrate this more concretely, consider the schema in the issue overview:

```
o2m:
  data: [1.0, -1.0, 2.0, 3.0, -1.0, 4.0, 5.0, 6.0]
  indices: [0, 2, 3, 5, 6, 7]
  sizes: [1, 2, 3]
  offsets: [0, 1, 3]
```

If we had an iterator `O2MIterator o2m_iter(o2m)` that we invoked `next()` on that iterator 4 times (note that, in Conduit, the first `next()` puts the iterator on the first element), then the values of the `index` operations would be:

- `o2m_iter.index(IndexType::DATA) == 5`: The 4th valid data item (i.e. `o2m["indices"][4]) is at index 5.
- `o2m_iter.index(IndexType::ONE) == 2`: The 4th valid data item is in the 3rd (index 2) "one" set.
- `o2m_iter.index(IndexType::MANY) == 0`: The 4th valid data item is 1st (index 0) in the context of its "one" set (length 3).

I hope that this helps and is intuitive, but I'm certainly open to improving the names for these functions in the interest of clarity.

**Comment by agcapps** [comment]
This does help.  With the explanation above, it feels consistent with the rest of Conduit in a "relaxed" (not "strained") way.

In your example you invoked `next()` four times.  If you then invoked `previous(IndexType::MANY)` one time, what should happen?  If you instead invoked `previous(IndexType::ONE)` one time, what should happen?

**Comment by xjrc** [comment]
Invoking `previous(IndexType::MANY)` would result in putting the iterator one before the beginning of the third "one" set. This is a valid position for the iterator to be in (this is, for example, the location of each iteration on construction relative to the first "one" set), but the index returned is effectively a garbage value. To avoid this circumstance, it's best to call `has_previous(IndexType::MANY)` before arbitrary calls to `previous(IndexType::MANY)`, which would return `false` in the initial state we're discussing.

As for `previous(IndexType::ONE)`, the iterator would point to the first item in the second (index 1) "one" set, which is 2.0 (index 2) in our example. Broadly speaking, this type of iteration is useful if we need to operate over a particular "many" index across "one"s. There are some weird edge cases with this style of iteration that we need to figure out (e.g what happens if we're at "many" index 5 for a "one" set of length 10 and `next(IndexType::ONE)` is called into a "one" set of length 2), but I think conceptually the process is straightforward.

**Comment by cyrush** [comment]
quick note: enums might not translate as well in the c, python, fortran cases vs functions?

**Comment by xjrc** [comment]
If this is how [`conduit::DataType`](https://github.com/LLNL/conduit/blob/213659212af810c5eb9ac82158b3482d1680bf6d/src/libs/conduit/conduit_data_type.hpp#L96) gets around this `enum`-related limitation, then extra functions are worth considering.

**Comment by cyrush** [comment]
supporting both styles (using an enum and having some set of functions) would be fine

**Comment by xjrc** [comment]
@cyrush Does that mean changing the interface to something like the outline below?

```
enum IndexType:
  DATA
  ONE
  MANY

class O2MIterator:
  // values/properties
  index_t index(IndexType itype);
  index_t elements(IndexType itype);

  // forward iteration
  bool has_next(IndexType itype);
  index_t next(IndexType itype);
  index_t peek_next(IndexType itype);
  void to_front(IndexType itype);

  // backward iteration
  bool has_previous(IndexType itype);
  index_t previous(IndexType itype);
  index_t peek_previous(IndexType itype);
  void to_back(IndexType itype);

  // human-readable information
  void info(Node& res)

  // c interface
  index_t index_data();
  index_t index_one();
  index_t index_many();

  index_t elements_data();
  index_t elements_one();
  index_t elements_many();

  // etc //
```

Or does supporting a C-style interface entail implementing something akin to [`src/libs/conduit/c/conduit_datatype_c.cpp`](https://github.com/LLNL/conduit/blob/master/src/libs/conduit/c/conduit_datatype_c.cpp)?

**Comment by cyrush** [comment]
i think fortran might be the important driver for the c-interface, honestly not sure what that should look like.  Let's work things out in C++ and then see how they evolve with some more use.
