### ISSUE TITLE
Merge save in append mode?

### ISSUE THREAD

**Issue by aowen87** [LLNL/conduit#587]
Is there any way to save a node to disk so that it appends to data in an existing array without loading that array back into memory? For instance, let's say I have a program that creates a node that looks like
```
{ "my_array" : [0.0, 1.0, 2.0] }
```
and it saves this to disk. It then deletes the local node from memory (not the one on disk, just the one created in memory) and goes about doing other things. Later on, it decides to make a new node that looks like this:
```
{ "my_array" : [3.0, 4.0, 5.0] }
```
What I'd like is to be able to perform a merge_save that ends up with a saved node that looks like:
```
{ "my_array" : [0.0, 1.0, 2.0, 3.0, 4.0, 5.0] }
```
But I don't want to read the originally saved node back into memory (imagine the array on disk is huge). 

Instead, what currently happens is the merge_save will overwrite the existing array, or, if I give it a new name like "my_array_2", it will create an entirely new array and add it to the saved node.

**Comment by cyrush** [comment]
HDF5 has a mechanism to do this with unlimited dims. For other cases I/O formats (YAML, JSON, Conduit Bin) those would have to be re-written. 

For HDF5, it would take some work to plumb. I expect the support in conduit would be a Relay HDF5 Specific API call that would be expect an array and some extra info.

Q: Would you be up for over-allocating to an expected size, and then using writes that accept offsets as a way to update?

**Comment by aowen87** [comment]
The only issue I can see with over-allocating for the first write is that there's no way for us to know how much space we need at the onset... each append would be data from a simulation cycle, and we typically run the sim until either some goal time is reached or the simulation crashes, which both happen at an unknown cycle. 

This append ability isn't a make or break scenario for us, though. It would just be a nice feature. A current workaround is to just label each cycle in the node:
```

for cur_cycle in sim do:
    //sim stuff, collect data, etc.
    cycle_tag = "my_array/cycle_%i" % cur_cycle
    node[cycle_tag] = cycle_data
    save_merged(node)
    node.reset()
    // do more sim stuff
```
This works, it's just that the data isn't exactly in the shape we'd like. We can do some extra work to re-organize after the write if we need to.

**Comment by cyrush** [comment]
Randy Settgast may also be interested in this.

**Comment by cyrush** [comment]
we now have this support from #709 and #715
