### ISSUE TITLE
spack concretization selecting charmpp for mpi, which fails to build

### ISSUE THREAD

**Issue by adammoody** [LLNL/conduit#601]
As a heads up, I'm finding my conduit builds tripping up on charmpp during the spack install of dependencies when trying to name a spec as in:

```source bootstrap-env.sh --spec '%gcc@8.1.0'```

Apparently spack is trying to use charmpp to fill the role of the MPI dependency (related issue https://github.com/spack/spack/issues/15521)

```
--------------------------------
uberenv-conduit%gcc@8.1.0

Concretized
--------------------------------
uberenv-conduit@0.0.0%gcc@8.1.0~adios+doc~doxygen+fortran+hdf5+hdf5_compat+mpi+python+shared~silo+test+zfp arch=linux-rhel7-broadwell
    ^charmpp@6.9.0%gcc@8.1.0 backend=gni build-target=AMPI ~cuda~omp~papi+production~pthreads+shared+smp~syncft~tcp~tracing arch=linux-rhel7-broadwell
```

Additionally, charmpp fails to build with ```backend=gni``` on some systems.

```
==> No patches needed for charmpp
==> Building charmpp [Package]
==> Executing phase: 'install'
==> Error: InstallError: The communication mechanism gni is not supported on a linux platform with a x86_64 CPU
```

As a work around, it seems like one can force spack to use mvapich2:

```source bootstrap-env.sh --spec '%gcc@8.1.0 ^mvapich2'```

**Comment by mclarsen** [comment]
When there is no config that specifies what mpi's to use, spack chooses alphabetically, so you get charm++. Probably the worst possible choice, and its probably best just to set it. I guess one could possibly add a conflict with charm++.

**Comment by mclarsen** [comment]
maybe we should just make a copy of the mvapich package called `aaaaaaaaamvapich`.

**Comment by cyrush** [comment]
Ahh, the charm surprise, I should add docs that say if spack starts building charm++ something is really off the rails. For linux systems we don't have a default `packages.yaml `, it's a good idea to try to create one following examples, maybe our docker one is a good place to start (although it uses a system mpi)
https://github.com/LLNL/conduit/blob/master/scripts/uberenv/spack_configs/docker/ubuntu/packages.yaml

**Comment by adammoody** [comment]
I think it was hitting this error on this packages.yaml:
https://github.com/LLNL/conduit/blob/master/scripts/uberenv/spack_configs/toss_3_x86_64_ib/packages.yaml

**Comment by gonsie** [comment]
you can add a “buildable: false” line to mark all MPIs as non-buildable to spack.

```
packages:
  mpi:
    buildable: False
```
