### ISSUE TITLE
Incorrect docs explanation of set semantics for compatible nodes

### ISSUE THREAD

**Issue by SeifIbrahim** [LLNL/conduit#607]
The docs suggest that `a.set(b)` will not change the schema of `a` if it is compatible with the schema of `b` and will simply copy. This is not true if `a` and  `b` are nodes.

https://llnl-conduit.readthedocs.io/en/latest/tutorial_cpp_basics.html#compatible-schemas
https://llnl-conduit.readthedocs.io/en/latest/tutorial_python_basics.html#compatible-schemas
https://llnl-conduit.readthedocs.io/en/latest/tutorial_cpp_update.html#node-update-methods

**Comment by cyrush** [comment]
resolved in #617
