### ISSUE TITLE
conduit::blueprint::mpi::mesh::generate_index

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#618]
Just a comment/suggestion about this function in conduit::blueprint::mpi::mesh

```
void CONDUIT_BLUEPRINT_API generate_index(const conduit::Node &mesh,
                                          const std::string &ref_path,
                                          Node &index_out,
                                          MPI_Comm comm);
```

This is an MPI collective call, so all ranks must pass an `index_out` Node, but only one rank fills the Node with any data.  Looks like it will be rank 0 as long as it has any domains on that rank, but in general you don't know.  This means that the calling code needs to inspect `index_out` before doing anything with it subsequently, especially if it intends to pass it along to something that expects a non-empty Node.

I can deal with this by inspecting the DataType of the Node, and if it's an object, it must contain the generated index, but would it make sense to add something to to API that explicitly tells us which rank has the index in the Node?  Some possibilities would be to make the rank the return value, or to add an `Node& info` to the signature as a place to put a small amount of metadata.

**Comment by cyrush** [comment]
Thanks for the feedback -- I think I should simply fix to broadcast so that all ranks get the resulting index. 
Seems like the easiest interface contract?

**Comment by nselliott** [comment]
That's fine--I thought it may have been a choice to avoid the broadcast overhead.  When I first looked at this, I assumed that the index would exist everywhere.

**Comment by cyrush** [comment]
Great ---  I'll go with that.
