### ISSUE TITLE
mesh bp struct topo: i,j,k origin, instead of i0,j0,k0 ?

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#622]
For logical offsets in topology entry, should we be using `{i,j,k}` instead of `{i0,j0,k0}`

What `{i0,j0,k0}` implies seems slightly more confusing in a dist-mem context, so `{i,j,k}` might be better.

Discuss.

**Comment by mclarsen** [comment]
`{i,j,k}` fits better in my mind. Its unique because of the path `topo/element/origin`

**Comment by nselliott** [comment]
I like {i,j,k} as well.
