### ISSUE TITLE
t_blueprint_mesh_generate crashes on Windows

### ISSUE THREAD

**Issue by agcapps** [LLNL/conduit#623]
In the t_blueprint_mesh_generate test, there is a `TopologyMetadata` object constructed.  In that ctor the polygonal mesh size is calculated, and stored into the first element of a zero-length(!) `std::vector`.  Linux is laid-back and lets it pass, but on Windows the test crashes.

The test t_blueprint_mesh_verify passes on Linux but fails on Windows.  This may be related.  If fixing this problem does not make t_blueprint_mesh_verify start to pass, I'll open a seperate issue for that.

**Comment by cyrush** [comment]
good detective work @agcapps -- I am surprised we didn't see this in windows CI testing.

**Comment by agcapps** [comment]
Me too.  That's another wrinkle that I'll need to figure out.

**Comment by agcapps** [comment]
Further detail:
- Compiling with MSVC
  - Debug: t_blueprint_mesh_generate segfaults, verify fails
  - Release: all succeed
- Compiling with MS Visual Studio driving Intel 19.0:
  - Debug: t_blueprint_mesh_generate segfaults (verify passes)
  - Release: all succeed

**Comment by agcapps** [comment]
@xjrc , this change removes the check whether `dim_shape.embedding == NULL`.

Why do `is_poly()`, `is_polyhedral()`, `is_polygonal()` check whether `embedding == NULL`?  Put differently, what does `foo.is_poly*() -> true` mean about `foo`?

**Comment by cyrush** [comment]
@agcapps  -- thanks for the details on the build options, currently appveyor compiles with default cmake build type setting (which I think is RelWDebugSym), so that seems to account for why it passes there. Perhaps we should use build type == debug since its much more stringent.

**Comment by cyrush** [comment]
@agcapps  can you point me where the bad write occurs? I am running valgrind and nothing appeared, but there are a bunch of std:vectors in the TopoMetadata class -- where did you see if first?

**Comment by agcapps** [comment]
Sure: in src/libs/blueprint/conduit_blueprint_mesh.cpp around line 1300, there's a for-loop labeled with the comment `// Transform Topological Data to Nodes //`.  In that for-loop, guarded by `if (di == 2)`, there is a constructor:

    `Node data_size(DataType::int64(dim_sizes[di].size()), &(dim_sizes[di][0]), true);`

Here, `dim_sizes` has type `std::vector< std::vector<int64> >` and length 3.  Without the change in PR #624 , all three elements of `dim_sizes` have length 0.  So the access (even to take the address) of the first element of zero-length `dim_sizes[di]` is not OK.

**Comment by cyrush** [comment]
I have been staring at this, having a hard time interpreting. My problem seems to be that I think the concept of a `dim` is overloaded in more than one way in the TopoMetadata class, at least enough to bend my brain.

For the following:

https://github.com/LLNL/conduit/blob/14d8cb7009d31e16b29635b7f6932f70eb257f04/src/libs/blueprint/conduit_blueprint_mesh.cpp#L1309

I guess the loop over `di` is looping over the dimensional cascade? 

I *think*, the check: (di == 2) -- should be asking if the entity is polygonal in another way, not just using topo dim == 2.
B/c that case could also exist for an unstruct grid that specifies a single shape type that all elements use. 

We should only be setting the sizes in that way if they weren't specified implicitly via a single shape -- I think thats is what is leading to the out of bounds. 

@bmhan12  You may have the best context here, can you take a look at this code and help us figure out what the right test should be?

**Comment by cyrush** [comment]
forgot to say thanks @agcapps for providing those details!

**Comment by bmhan12** [comment]
@cyrush Yes, this loop is for initializing [dim_topos](https://github.com/LLNL/conduit/blob/14d8cb7009d31e16b29635b7f6932f70eb257f04/src/libs/blueprint/conduit_blueprint_mesh.cpp#L1469), which is a vector of Nodes, each index containing the topology at the ith dimension. The motivation behind the ` (di == 2)` check is for `generate_X` function calls with 3D `shape: polyhedral` Node inputs. The` elements/sizes` field was not being initialized for the 2D polygonal topology Node in `dim_topos`, so I added `dim_sizes` to iteratively initialize the sizes and then set the values.  I just realized this is why `dim_sizes` will be empty most of the time (only filled for the 2nd dimension and that is only for a polyhedral input), and I can do the same thing by initializing the `elements/sizes` field of the polygonal Node to the `subelements/sizes` field of the polyhedral Node.

I put up PR https://github.com/LLNL/conduit/pull/632 to remove `dim_sizes` and implemented the simpler check and initialization for the polyhedral input case.

**Comment by cyrush** [comment]
this should be resolved in #632, but we should double check on a windows system

**Comment by agcapps** [comment]
@cyrush , I verified that @bmhan12 's changes in #632 fix this problem.  Thank-you.

Closing as resolved.

**Comment by agcapps** [comment]
Closing as resolved.
