### ISSUE TITLE
Size check?

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#625]
https://github.com/LLNL/conduit/blob/09b49e839add9e46707c458ea463928f87a2c1c1/src/libs/relay/conduit_relay_mpi.cpp#L770

if `index_t` is not an int, there should probably be a check here that makes sure this cast doesn't result in chaos.

**Comment by cyrush** [comment]
`index_t` will always be signed, so we should be good with that aspect.  `static_cast` should call an implicit conversion even between 64-bit and 32-bit ints?  I think this should be safe except for extremely huge data sizes, and only if index_t is a 64-bit and int is 32.

`reinterpret_cast` would be the horrifying one to use here? Is that what you are worried might be happening?

**Comment by mclarsen** [comment]
if `index_t` is 64bit and the number of bytes is > an int32, then the resulting size will be incorrect. Maybe this results in an MPI error or maybe it doesn't. Either way, the resulting failure would be hard to figure out. What I don't know is what `index_t` is.

**Comment by cyrush** [comment]
i agree having a check would be good

**Comment by xjrc** [comment]
This feature has also been requested by @aaroncblack.

**Comment by cyrush** [comment]
I also think we can simplify a lot of  int vs index_t, etc logic if we attack:

https://github.com/LLNL/conduit/issues/339

**Comment by cyrush** [comment]
I need to think about this a bit more.

Compile time we could complain if the `index_t` range is bigger than mpi can accept. But that would needlessly limit many cases that would work.

At runtime we could check exactly when the size is bigger than MPI can handle.  But what is the best way to alert folks? An except will be a ticket to a MPI hang.
