### ISSUE TITLE
Summary argument to node.print()

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#670]
It would be nice to have summary style print method for printing out trees with very large leaves (fields). Example:

```
node.print(5)
```
would only print out the first five values of a leaf.

**Comment by cyrush** [comment]
partially resolved by `Node::detail` method,  will be full resolved with`Node::to_summary_string` #674

**Comment by cyrush** [comment]
resolved addition of `Node::describe` and  `Node::to_summary_string`
