### ISSUE TITLE
Clarify documentation for nestset window schema for origin coordinates

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#678]
I had some difficulties in an attempt to provide nestset information to Ascent, because the values I provided for `nestsets/nestset/windows/window/origin/{i, j, k}` were based on a global coordinate system rather than the local topology for each domain, while Ascent was coded to expect the origin to be based on the local topology.  I don't recall if this was discussed specifically when we devised the nestset schema, or if I was just working off of my own faulty assumptions and biases, but I think what I did was incorrect because we can't assume there is any global coordinate system defined for the topologies.  It is not explicitly stated in the documentation what is the correct approach, so it could be useful to add something to clarify this.  I am working on fixing the code in SAMRAI that I use to compute these values.

**Comment by cyrush** [comment]
resolved in #712
