### ISSUE TITLE
Exported `conduit::conduit` has non-existant path in INTERFACE_INCLUDE_DIRECTORIES

### ISSUE THREAD

**Issue by white238** [LLNL/conduit#679]
I get the following error when importing Conduit into Axom:

```
CMake Error in axom/CMakeLists.txt:
  Imported target "conduit::conduit" includes non-existent path

    "/usr/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

This seems to be a combination of OSX deprecating `/usr/include` and hdf5 adding a path that doesnt exist to it's include directories.

I could filter this from the target you export on your side or filter it incoming on Axom.  Thoughts?

**Comment by cyrush** [comment]
this is with cmake 3.19.2

**Comment by cyrush** [comment]
@white238  -- what version of HDF5, and was it built with cmake or not?

**Comment by white238** [comment]
hdf5 version 1.8.21 built with autoconf via spack

**Comment by cyrush** [comment]
@white238 I haven't been able to trigger this yet. It does seem you are mixing homebrew and spack. I wonder if the path issue is due to what HDF5 is reporting b/c it is compiling against the homebrew mpich. 

If you aren't already, can you see if there is an issue if you build with `hdf5~mpi` ?

(For your use case -- you don't need hdf5 to have mpi support)

**Comment by joshessman-llnl** [comment]
After some investigation with @jandrej it was determined that the culprit may be a combination of [this logic](https://github.com/LLNL/conduit/blob/develop/src/config/conduit_setup_targets.cmake#L6-L9) and the fact that Conduit duplicates its CMake package files:
- once in `<install_dir>/lib/cmake`
- once in `<install_dir>/lib/cmake/conduit`

The logic linked above assumes that the installation directory is three levels up from the Conduit package files and thus that only the files in the latter location are used.  If the config files in the former location are found, this will result in nonexistent paths being added to the `conduit::conduit` target.

See https://cmake.org/cmake/help/v3.20/command/find_package.html#search-procedure for a listing of the paths CMake will use to locate these package files.

Would it be possible to remove this duplication so the hardcoded path traversal logic in `conduit_setup_targets.cmake` can be made unconditionally correct?

See:

https://github.com/spack/spack/pull/23377#issuecomment-830464468
https://github.com/LLNL/serac/pull/456
https://github.com/LLNL/axom/issues/530
https://github.com/LLNL/axom/pull/540

**Comment by cyrush** [comment]
Makes sense. The duplication logic was there as a stop gap for when it changed from less ideal setup to a more standard cmake standard setup (the one with the project name included)

I will remove:

`<install_dir>/lib/cmake`

and keep:
`<install_dir>/lib/cmake/conduit`

Sound good?

**Comment by white238** [comment]
A+ detective work @joshessman-llnl ! Thanks for tracking this down.

**Comment by cyrush** [comment]
note, post this change -- axom will need to adapt this check:

https://github.com/LLNL/axom/blob/c4e24c7ffe2e44001db5e33c74fc583b8d9c4bae/src/cmake/thirdparty/FindConduit.cmake#L22
