### ISSUE TITLE
CONDUIT_INSTALL_PREFIX

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#721]
How does this variable get populated? Its not used and super confusing.

**Comment by cyrush** [comment]
It's used to propagate/store the install prefix, passed by -DCMAKE_INSTALL_PREFIX so it the install location can be accessed at runtime. It's set in `libs/conduit/CMakelists.txt`

**Comment by cyrush** [comment]
confusion here:

This seems like something you can set in `ccmake`, but that's not the case. 

It's a var we use to orchestrate locating the final install dir and to setup our exported targets.

We should mark it as advanced, so its less prominent in ccmake.
