### ISSUE TITLE
python: should str() also use summary string?

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#734]
for large data, `repr` works great, but if you `print()` a node you can get into trouble.

Should default `str` also use summary string. Folks that want the whole string can still use `to_yaml`, etc.

**Comment by cyrush** [comment]
logic could also apply to print() in c++ and fortran (not sure if we made that change yet)

**Comment by cyrush** [comment]
c++ logic does not use summary string, I think it should -- possibly starting with `0.8.0`

https://github.com/LLNL/conduit/blob/c61109247de101e7c0c542b70b7e59ea48d85391/src/libs/conduit/conduit_node.cpp#L13218

**Comment by xjrc** [comment]
I endorse this change.
