### ISSUE TITLE
Potential Magic Memory Solution for sharing between packages

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#776]
Scenario 1: 
Data provider has GPU memory in a tree.
Data consumer can only handle host memory.

Magic:
Provide a way to magically interface and zero copy memory only if it exists on CPU, otherwise make a copy to the host.

Scenario 2: 
Data provider has GPU memory in a tree.
Data consumer can handle GPU memory

Magic:
zero copy all pointers.

Specialized allocators could handle this but we lack an interface to only zero copy if X.

**Comment by cyrush** [comment]
If my memory serves me correctly: 

We checked the spell book and discovered this was a dangerous type of magic, for which we should not wield. 

@mclarsen let me know if I have it right.

**Comment by rhornung67** [comment]
Where can I get one of those "spell books"? I need some magic.

**Comment by cyrush** [comment]
Closing since this is not the magic we are looking for.
