### ISSUE TITLE
add in-place `generate_offsets` function

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#783]
There are a number of places where the `conduit::blueprint::mesh::topology::unstructured::generate_offsets` function is used to generate offsets in their default path (i.e. for input topology `n`, at path `n["elements/offsets"]`). In order to reduce the technical burden of pre-generating these offsets for internal code and savvy users, a non-const, in-situ alternative should be provided with an interface like `conduit::blueprint::mesh::topology::unstructured::generate_offsets(Node &n)`.

**Comment by cyrush** [comment]
Resolved in https://github.com/LLNL/conduit/pull/1037
