### ISSUE TITLE
`conduit_blueprint_verify` tool cannot process basic JSON/YAML files

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#784]
The `conduit_blueprint_verify` tool fails to recognize basic JSON and YAML inputs. Attempting to submit JSON and YAML equivalents of [the rudimentary Blueprint rectilinear mesh example](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#rectilinear) causes the following errors:

### JSON ###

```
$ cat example.json
{
  "coordsets": 
  {
    "coords": 
    {
      "type": "rectilinear",
      "values": 
      {
        "x": [-10.0, 0.0, 10.0],
        "y": [-10.0, 0.0, 10.0]
      }
    }
  },
  "topologies": 
  {
    "mesh": 
    {
      "type": "rectilinear",
      "coordset": "coords"
    }
  },
  "fields": 
  {
    "field": 
    {
      "association": "element",
      "topology": "mesh",
      "volume_dependent": "false",
      "values": [0.0, 1.0, 2.0, 3.0]
    }
  }
}
$ ./conduit_blueprint_verify json example.json
conduit::blueprint::verify FAILED
verify info:

```

### YAML ###

```
$ cat example.yaml
coordsets: 
  coords: 
    type: "rectilinear"
    values: 
      x: [-10.0, 0.0, 10.0]
      y: [-10.0, 0.0, 10.0]
topologies: 
  mesh: 
    type: "rectilinear"
    coordset: "coords"
fields: 
  field: 
    association: "element"
    topology: "mesh"
    volume_dependent: "false"
    values: [0.0, 1.0, 2.0, 3.0]
$ ./conduit_blueprint_verify yaml example.yaml
conduit::blueprint::verify FAILED
verify info:

```

This should be fixed so that `conduit_blueprint_verify` can be used to verify simple JSON and YAML meshes.

**Comment by cyrush** [comment]
can confirm -- segfault with no protocol arg, and confusing messages when try to provide the protocol

```
[harrison37@elder conduit (develop)]$ build-debug/libs/blueprint/conduit_blueprint_verify  --relay-protocol  yaml here.yaml 
Error launching running conduit::blueprint::verify

file: /Users/harrison37/Work/github/llnl/conduit/src/libs/conduit/conduit_node.cpp
line: 355
message: 
<Node::load> failed to open: yaml

usage: conduit_blueprint_verify {blueprint-protocol} {data file} 

 optional arguments:
  --relay-protocol {protocol to use for reading with relay }
```

**Comment by cyrush** [comment]
Ok, the confusion here is b/c there are two protocols to specify:

One is the `blueprint` protocol (such as `mesh`), which you always need to provide. 
The the other is the optional relay protocol (like `hdf5`). 

To provide this, you use the `--relay-protocol` option. 

Here are two working examples:

`./build-debug/libs/blueprint/conduit_blueprint_verify  mesh example.yaml`

`./build-debug/libs/blueprint/conduit_blueprint_verify  mesh example.yaml --relay-protocol=yaml`

I think our minds snap right to mesh blueprint verify, so there should be a standalone exec for that (very common) use case. 

I will also improve the usage message for this exe.
