### ISSUE TITLE
better func sig for generate_functions 

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#794]
From the header file:

https://github.com/LLNL/conduit/blob/d7f9ac7edef861f8b57a9e4abd579c50e5d9715e/src/libs/blueprint/conduit_blueprint_mesh.hpp#L319

It's hard to tell that `Node &n` is implied to be a valid blueprint topology. 

We should change these to `topo` in the header. (Note these are topo in the cpp file)

**Comment by xjrc** [comment]
I'm in favor of this change.
