### ISSUE TITLE
silo write support doesn't conform to current blueprint specs 

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#808]
This comment is 100% correct: 

https://github.com/LLNL/conduit/blame/develop/src/libs/relay/conduit_relay_io_silo.cpp#L293

Silo support was added while the basic mesh blueprint was in flux, it needs to be reworked.

**Comment by cyrush** [comment]
@JustinPrivitera can we close this with your improvements?

**Comment by JustinPrivitera** [comment]
I would expect yes. The problem is that the link up above no longer links to any comment, so it is unclear exactly what the original problem was.
