### ISSUE TITLE
Potential memory leak in Node::set_string

### ISSUE THREAD

**Issue by Laganellac** [LLNL/conduit#859]
I noticed this yesterday when running valgrind over one of blueprint::table tests I was working on. Currently checked out on develop at 3363fa08.

Here's a small program that causes valgrind to report errors.

```cpp
#include <conduit_node.hpp>

using namespace conduit;

int main(int argc, char *argv[])
{
    Node node;
    node["leak"] = "I wont be destroyed!";
    return 0;
}
```

I've also attached the output of valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all

[valgrind.out.txt](https://github.com/LLNL/conduit/files/7469223/valgrind.out.txt)

**Comment by cyrush** [comment]
thanks @Laganellac.  I'll take a look, might be related to our new memory handlers.

**Comment by cyrush** [comment]
@Laganellac, I think this leak might be the memory handler itself, not the string.

Your string would be `21` bytes, but we don't have a leak of that size. 

As for the memory handler leak, brace yourself -- we leak the handler on purpose. 

If you are curious why the handler is leaked, here is a note that explains that choice:

https://github.com/LLNL/conduit/blob/f18da11d51da7862eec5780687272fdb8bfe35dc/src/libs/conduit/conduit_utils.cpp#L144

**Comment by Laganellac** [comment]
@cyrush Okay good to know!
