### ISSUE TITLE
Support HDF5 1.12+

### ISSUE THREAD

**Issue by ax3l** [LLNL/conduit#896]
Conduit as of 0.7.2 requires the HDF5 APIs <=1.10: https://github.com/spack/spack/pull/28091

This should be relaxed to _also_ work with newer HDF5 versions, i.e., the 1.12 and 1.13 API conventions. (Ideally without dropping support for the 1.8 and 1.10 APIs of HDF5.)

**Comment by cyrush** [comment]
@ax3l with the `0.8.0` release, I added support for HDF5 1.12 - with our unit tests passing. 

Conduit can still be compiled against HDF5 1.8.x and 1.0.x.  I haven't tested 1.13.

So I think this support is here with the new release, but I am not sure if you have had a chance to leverage that.

**Comment by cyrush** [comment]
@ax3l  I am going to close, since we have this in our latest release and we have a HDF5 1.12 case in our CI. If you have any new problems please let me know with a new issue.

**Comment by ax3l** [comment]
Awesome, thanks a lot @cyrush !
