### ISSUE TITLE
Extend Mesh Blueprint for mesh meta-data (aka FieldData in VTK world)

### ISSUE THREAD

**Issue by francois-kitware** [LLNL/conduit#897]
Hello,

in the context of ParaView's Catalyst2 library, which uses conduit nodes intensively, we need to support the VTK's FieldData. FieldData is associated to a data object (a mesh in conduit world) and it contains several arrays to describe global properties of the mesh. The arrays are not associated to vertex nor element.
Some examples : save the time at which the data were recorded, save the name of the author of the dataset, store extra information on surfaces, save domain specific properties, etc.
There are no restrictions about the length of arrays that are added to the FieldData. 

At the moment, I can imagine several ways to extend mesh blueprint protocol:
 - allow "none" in the `fields/field/association` key
 - extend `state` to support arbitrary data
 - new child named `meta`

Do not hesitate to suggest other way to support the FieldData, as I probably don't have the big picture.

**Comment by cyrush** [comment]
@francois-kitware I think the best place for this type of info is in `state`. 

In fact, you could start experimenting with that as a solution right now -- because the blueprint verify should not complain if you add extra nodes under state. 

Longer term, we could think about formally extending the blueprint to support these as optional constructs.

**Comment by francois-kitware** [comment]
@cyrush Thanks for the quick answer!

So, we'll start the implementation with the `state` node and eventually report it here for suggestion and potential official support in the future.

**Comment by francois-kitware** [comment]
Hello,

just to mention that ParaView-Catalyst now supports the field-data via the `state` node. You can look at the [documentation](https://gitlab.kitware.com/paraview/paraview/-/blob/master/Utilities/Doxygen/pages/ParaViewCatalystProtocol.md):

>channel/data/state/fields/[field-name]: (optional) defines extra field associated to the current mesh.
The field is not associated to any topology and it could be a string, a numerical array or an array following the
[MCArray Blueprint](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mcarray.html) protocol.
In ParaView Catalyst, the field will be added as Field Data array to the generated VTK object.

Thanks @cyrush  for your guidance through the conduit protocol. I'm closing the issue.

Best,
François

**Comment by cyrush** [comment]
@francois-kitware, thanks for the update, glad this strategy is working for you!
