### ISSUE TITLE
git_archive_all confused by nested submodules

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#901]
`spack_configs` as a submodule, including radiuss spack configs as a submodule trips up git_archive_all

Had to edit git_archive_all to produce release tarballs. 

we aren't using the radiuss spack configs yet, so near term we can remove them, but it would be good to know what is going wrong.

**Comment by rhornung67** [comment]
@cyrush if it's any help, here's an example of what we do in RAJA, Axom, Umpire, etc. https://github.com/LLNL/RAJA/blob/develop/scripts/make_release_tarball.sh
