### ISSUE TITLE
src/libs/blueprint/conduit_blueprint_mpi_mesh_parmetis.cpp need to #include <algorithm>?

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/conduit#913]
I am trying to build conduit-0.8.1 in spack and got this error:

```
/tmp/lee218/spack-stage/spack-stage-conduit-0.8.1-bmqqtmgvjptitcw3gj3xie6jcfnaj6au/spack-src/src/libs/blueprint/conduit_blueprint_mpi_mesh_parmetis.cpp:451:18: error: 'sort' is not a member of 'std'
             std::sort(recv_groups.begin(), recv_groups.end());
```

Should this source file ```#include <algorithm>```?

**Comment by cyrush** [comment]
@lee218llnl -- thanks for the report -- what compiler are you using? 

For a quick fix, we can add a patch to the spack package.

**Comment by lee218llnl** [comment]
$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)

**Comment by lee218llnl** [comment]
I should add that this is for TOSS 4, so you can test on corona if you have access

**Comment by cyrush** [comment]
thanks, I'll take a look!

**Comment by lee218llnl** [comment]
I created a patch in my personal copy of spack, so no rush on this. I could submit a PR to spack if you like, but I'm not sure which release versions of conduit this would apply to.

**Comment by cyrush** [comment]
Great -  the patch would apply to `0.8.0` and `0.8.1` (that feature is new starting in `0.8.0`. If you can add it to spack that would be great, or I can do it later this week.

**Comment by lee218llnl** [comment]
It looks like 0.8.0 doesn't use std::sort, so I just added 0.8.1 to the spack package along with a patch that just includes the algorithm header.

**Comment by lee218llnl** [comment]
do you need me to submit a PR to conduit itself?

**Comment by cyrush** [comment]
that would be great :-)
