### ISSUE TITLE
Request: Add function to retrieve node that throws exception if path or child not found.

### ISSUE THREAD

**Issue by aaroncblack** [LLNL/conduit#933]
Conduit has the following functions for retrieving nodes in a tree:
- fetch
- operator []

I believe both of these functions will auto-insert a missing entry and then return the new node, similar to the C++ std::map operator[] function.

I think another function that does not auto-insert a node would be handy, the equivalent of the c++ std::map at() function.

This would be considered something for 'convenience', as developers can currently do this:
if (!node.has_path("some/child")
{
   throw an out of range exception
}
foo = node.fetch("some/child")

**Comment by aaroncblack** [comment]
fetch_existing() provides this functionality!

**Comment by cyrush** [comment]
@aaroncblack 

You can use `fetch_existing` for this case:

https://github.com/LLNL/conduit/blob/af5adda7c6dc30d3ebe1e0f34fa1c25f47fa58c7/src/libs/conduit/conduit_node.hpp#L3890

You can also use the `operator::[]` when you have `const Node &`
