### ISSUE TITLE
add_subdirectory support

### ISSUE THREAD

**Issue by andrewcorrigan** [LLNL/conduit#964]
I am working on adding conduit to a project and see the documentation [1] that shows how to do so using `find_package`.  I tried instead doing so using `add_subdirectory` 

```
 add_subdirectory(${third_party}/conduit/src)
```

This creates a target named `conduit`, but when I add this target as a dependency to my executable, it doesn't set include directories leading to errors like:

```
fatal error: 'conduit.hpp' file not found
#include <conduit.hpp>
```

1. Is `add_subdirectory` supported currently?  If so, is there documentation or any tips on correct usage?
2. If I'm not missing something obvious and this usage is currently not supported, would there be interest in a contribution to specify `target_include_directories` to enable `add_subdirectory` usage?  I'd be interested in contributing this, if so.

[1] https://llnl-conduit.readthedocs.io/en/latest/quick_start.html#using-conduit-in-your-project

**Comment by cyrush** [comment]
@andrewcorrigan  thanks for the question.

I just want to make sure we understand the goal -- would you like to use the conduit lib only, or other libs as well?

One challenge beyond the peculiar build time include strategy we use (which I think you may have a fix for) is that the conduit lib uses object libraries elsewhere in the source tree as dependencies. 

Here is where they come in:

https://github.com/LLNL/conduit/blob/5c76805286b8018bc1d5b62a98e54f00d4c343bd/src/libs/conduit/CMakeLists.txt#L137

These are built-in thirdparty libs that exist under:

https://github.com/LLNL/conduit/tree/develop/src/thirdparty_builtin

I think it would be more robust to try to include the full conduit project as sub cmake project, but that can also be a challenge b/c fusing CMake build systems can lead to hard to diagnose surprises.

**Comment by andrewcorrigan** [comment]
Thanks for following up 😁

> I just want to make sure we understand the goal -- would you like to use the conduit lib only, or other libs as well?

I would like to use `conduit`, `conduit_relay`, `conduit_blueprint` and if there are internal dependencies on something like `silo` or `hdf5` for those to be inherited automatically (typical cmake target behavior).

> One challenge beyond the peculiar build time include strategy we use (which I think you may have a fix for) is that the conduit lib uses object libraries elsewhere in the source tree as dependencies.

I'll look into this, but so far, it hasn't been an issue, the `conduit`, `conduit_relay`, and `conduit_blueprint` targets already are taking care of linking to the static libs.  The relevant part of the linker line has:
```
...   ../lib/libRAJA.a ../lib/libcamp.a ../lib/libconduit_relay.a ../lib/libconduit_blueprint.a ../lib/libconduit.a. ...
```

Do these additional object libraries need to be linked against as well?  I haven't verified other dependencies yet like silo, hdf5, etc. but will make sure those get accounted for and report back here.

> I think it would be more robust to try to include the full conduit project as sub cmake project, but that can also be a challenge b/c fusing CMake build systems can lead to hard to diagnose surprises.

I'm pretty sure this is what I was describing originally.  My top level project has a subfolder containing conduit, which I pass as a relative path to `add_subdirectory`, which introduces the `conduit`, `conduit_relay`, and `conduit_blueprint` targets in that are introduced as dependencies in my project.

By the way, I don't disagree about any drawbacks of fusing cmake build systems, but I'm stuck with this approach for the time being (I'm interested in adopting spack but can't do it overnight).  Meanwhile, so far it's working adequately for many other dependencies, including raja, tbb, fmt, boost, vtk, cgns, abseil, glfw, among other more obscure third-party libraries.

**Comment by cyrush** [comment]
Great thanks for more context! I misunderstood at first and thought you were just trying to add the src/libs/conduit subdir, which would not have worked w/o the other cmake logic.

Happy to include your changes -- just merged the PR .
