### ISSUE TITLE
verify method for the Blueprint index

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#966]
We can call `verify()` on a mesh to confirm that it correctly follows the Blueprint schema, but is there anything analogous for the Blueprint index, to check that a Node that claims to hold a Blueprint index is following a valid schema for the index?

**Comment by cyrush** [comment]
hi @nselliott  -- yes, there is, it's `conduit::blueprint::mesh::index::verify`

**Comment by cyrush** [comment]
https://github.com/LLNL/conduit/blob/3edfd63095da3e7a94ea2ae4537abb5ae7b4b547/src/libs/blueprint/conduit_blueprint_mesh.hpp#L704

**Comment by nselliott** [comment]
Thanks @cyrush , somehow I overlooked that while looking all over.  Will give it a try.

**Comment by cyrush** [comment]
No worries!
