### ISSUE TITLE
Load from subpath broken with json

### ISSUE THREAD

**Issue by adayton1** [LLNL/conduit#997]
I'm hitting an exception when calling `conduit::relay::io::load(const std::string& path, conduit::Node& node)` using a subpath. My path is of the form `myDirectory/myFile.json:path/to/data`. The exception occurs at the following line:
https://github.com/LLNL/conduit/blob/develop/src/libs/conduit/conduit_node.cpp#L355. When examining in a debugger, the call to open the file uses the full string (`myDirectory/myFile.json:path/to/data`) rather than just the file name (`myDirectory/myFile.json`).

**Comment by cyrush** [comment]
Turns out support wasn't there yet, but I am adding in #999
